### PR TITLE
sonic-swss: Sync and program remote lag member status.

### PR DESCRIPTION
**Pull request by skbarista**
* SYSTEM_LAG_MEMBER_TABLE is updated to carry the member status.
   * Pass lag member status to addLagMember so that it can be updated in SYSTEM_LAG_MEMBER_TABLE.
   * In doLagMemberTask add code to update lag member status in SYSTEM_LAG_MEMBER_TABLE so that remote linecards can handle the member status.
   * Remove the code that ignore collecting/distributing update for members of remote lags.
   * Update voqSyncAddLagMember to update the lag member status.

**What I did**

Sync and program remote lag member status.

**Why I did it**

To fix the issue where remote lag memberships were not updated when the local lag memberships changes.

**How I verified it**

Verified that the traffic from remote linecards is redistributed to active members when a link goes down.

**Details if related**

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]
lgtm

**Comment by arlakshm** [comment]
@deepak-singhal0408  for viz..

**Comment by prsunny** [comment]
@skbarista , since this is requested for 202205, can you confirm the changes are tested on the target branch?

**Comment by skbarista** [comment]
@prsunny this has not been tested on 202205 yet. Will test and get back. Can we hold on to 202205 merge till then.

**Comment by prsunny** [comment]
> @prsunny this has not been tested on 202205 yet. Will test and get back. Can we hold on to 202205 merge till then.

Will do. @yxieca for viz

**Comment by skbarista** [comment]
@prsunny we validated this on 202205.  So this can be merged to 202205.

**Pull request merged**
