### PR TITLE
[buffermgrd] Move switch-statement outside of if-statement in BufferMgr::doTask

### PR DESCRIPTION
**Pull request by amazor**
Fix for: 
[swss] BUFFER_PG and BUFFER_QUEUE configs are not getting applied on new ports created from dynamic breakout #2865
and most l likely other bugs related to dynamic buffer management.

**What I did**
Fixed bug that would cause an infinite loop in buffermgr.cpp when sending a non-set command (eg. delete)

**Why I did it**
The Bug would cause buffermgrd to be stuck in infinite loop, blocking its function.

**How I verified it**
Buffer configuration after deletion of a port(eg. dynamic port breakout command) will now be correctly processed. This was checked through log outputs on buffermgrd

**Details if related**
The switch statement which would normally erase buffer events was moved to be inside the if-statement which would only enter if the event is a SET event. This was introduced in commit 5329c39.
This would cause an infinite loop, since non-set events would never be erased/consumed.
The switch statement has now been moved to occur outside the if, allowing for non-SET commands to be processed.

**Which release branch to backport** 
These branches should be updated as the bug exists on all of these releases:
- 202205
- 202211
- 202305
- 202311

### CODE REVIEW

**Review by matiAlfaro — APPROVED** [review]

**Review by neethajohn — APPROVED** [review]

**Review by stephenxs — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by amazor** [comment]
@prsunny Will this PR be backported to previous release branches as mentioned in the PR request?

> Which release branch to backport
> These branches should be updated as the bug exists on all of these releases:
> 
> - 202205
> - 202211
> - 202305
> - 202311

**Comment by amazor** [comment]
@prsunny, Can I get an update on the backport request? Is this done in a separate PR, or by the community?

**Comment by prsunny** [comment]
@amazor , i've marked for backporting to 2023 branch. 2022 is frozen for most backports.
Can you please confirm the test result for 202305 branch with this change before it can be approved for cherrypick?

**Pull request merged**
