### PR TITLE
Remove TODO comments which are no longer needed

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**What I did**

Remove TODO comments which are no longer needed

**Why I did it**

MUX support has already been removed, the TODO item is not valid

**How I verified it**

Only comment change

**Details if related**

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Review by oleksandrivantsiv — APPROVED** [review]

**Comment by prsunny** [comment]
Failures are being investigated - https://github.com/sonic-net/sonic-swss/issues/2570

**Comment by Junchao-Mellanox** [comment]
Hi @prsunny , all checkers have passed, could you please help merge this?

**Pull request merged**
