### PR TITLE
[202311][fpmsyncd][WR] Relax the static schema constraint for ROUTE_TABLE

### PR DESCRIPTION
**Pull request by vivekrnv**
**What I did**

Cherry pick https://github.com/sonic-net/sonic-swss/pull/2981

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by yxieca** [comment]
@dgsudharsan please look into the test failure. Thanks!

**Comment by vivekrnv** [comment]
The same three test, namely test_mysid, test_mysid_l3adj & test_srv6 have also failed in this run for the first time. This run is for a master PR on Mar 11 FYI.

https://dev.azure.com/mssonic/build/_build/results?buildId=496703&view=ms.vss-test-web.build-test-results-tab

2311 did not have the change specified in the PR used in above link. 

So, i tend to think the root cause of the failure is something else and this test appears to be flaky. Anyway retriggering now to see if this is solved

**Comment by vivekrnv** [comment]
@yxieca Can this PR be merged?

**Comment by yxieca** [comment]
@vivekrnv can you confirm that you have run test with this change with 202311 image?

**Comment by vivekrnv** [comment]
> @vivekrnv can you confirm that you have run test with this change with 202311 image?

Yes, the WR issue is fixed with this change.

**Pull request merged**
