### PR TITLE
[202205][CodeQL]: Use dependencies with relevant versions in azp template

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**What I did**
* Increase robustness of `CodeQL`: use only dependencies with the relevant versions

**Why I did it**
* To fix `CodeQL` compilation failures

**How I verified it**
1. Make a PR
2. Do a push

**Details if related**
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2845
* Takes effect only after PR is merged

### CODE REVIEW

**Comment by nazariig** [comment]
@yxieca just a kind reminder

**Review by vadymhlushko-mlnx — APPROVED** [review]

**Comment by qiluo-msft** [comment]
@liushilongbuaa Could you help review?

**Comment by nazariig** [comment]
@prsunny codeql will pass only after PR is merged: there is no point to restart the CI

**Comment by nazariig** [comment]
@prsunny / @yxieca can you please help to merge?

**Pull request merged**
