### PR TITLE
[portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it

### PR DESCRIPTION
**Pull request by stephenxs**
This is to
- revert the PR #2396 which reverted the original PR #2333
- adjust the compiling error introduced by #2333

**What I did**
Expose supported FEC modes to `STATE_DB.PORT_TABLE|<port>.supported_fecs`.
The orchagent calls `get_port_attribute` to get attribute `SAI_PORT_ATTR_SUPPORTED_FEC_MODE` during initialization and then records it into internal data.
   - By default, the supported FEC modes will be returned by SAI and exposed to `STATE_DB`. Eg. `rs,none` means only `rs` and `none` is supported on the port.
     - The orchagent will check whether the FEC mode is supported on the port before calling the SAI API to set it.
     - The CLI will check whether the FEC mode is in `supported_fecs` before setting FEC mode on a port to the `CONFIG_DB`
   - In case the SAI API does not support any FEC mode on the port, `N/A` will be exposed to `STATE_DB`
     - The orchagent will deny any FEC setting and prints log.
     - The CLI will deny FEC setting.
   - In case the SAI API `get_port_attribute` returns `Not implemented`
     - No check will be performed before setting a FEC mode to SAI on the port.
     - The CLI will check whether the FEC mode is defined before setting it to `CONFIG_DB`.

**Why I did it**
It is not supported to set FEC mode on some platforms. To avoid error, we need to expose the supported FEC list.

**How I verified it**
Manually test and mock test.

**Details if related**

### CODE REVIEW

**Comment by stephenxs** [comment]
@prsunny  @prgeor 
can you approve and merge this PR? It is to take PR #2333 back and fix the compiling issue. it contains 2 commits
1. revert the reverting PR
2. resolve the compiling issue
thank you.

**Comment by prsunny** [comment]
@prgeor , can you please sign-off/merge?

**Review by keboliu — APPROVED** [review]

**Review by keboliu — APPROVED** [review]

**Comment by keboliu** [comment]
@prgeor , would you please sign-off/merge?

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@stephenxs https://github.com/sonic-net/sonic-swss/pull/2400/commits/84a32e2e7b0a7098d238d9c9440c21f55e4df8b6 this commit doesnot seem right. lets discuss.

**Review by prgeor — CHANGES_REQUESTED** [review]
https://github.com/sonic-net/sonic-swss/pull/2400/commits/84a32e2e7b0a7098d238d9c9440c21f55e4df8b6 why merge from maser?

**Comment by stephenxs** [comment]
> [84a32e2](https://github.com/sonic-net/sonic-swss/commit/84a32e2e7b0a7098d238d9c9440c21f55e4df8b6) why merge from maser?

Merging master back is a common way to resolve conflicts. We do it in this way from time to time

**Review by prgeor — APPROVED** [review]

**Comment by yxieca** [comment]
@stephenxs this PR cannot be cherry picked cleanly to 202205 branch. Please raise separate PR.

**Pull request merged**
