### PR TITLE
[202205][Everflow/ERSPAN] Set correct destination port and mac address when the nexthop is updated for ERSPAN mirror destination

### PR DESCRIPTION
**Pull request by saksarav-nokia**
* [Everflow/ERSPAN] Set correct destination port and mac address when the nexthop is updated for ERSPAN mirror destination
* [Everflow] Fixed show mirror-session, Acl rule remove failure, orchagent crash

Signed-off-by: Sakthivadivu Saravanaraj <sakthivadivu.saravanaraj@nokia.com>

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by saksarav-nokia** [comment]
@prsunny , could you please add @gechiang as reviewer

**Comment by saksarav-nokia** [comment]
@gechiang , i have created this PR for 202205 as per your request

**Comment by gechiang** [comment]
This is porting of the same fix that went into master:
https://github.com/sonic-net/sonic-swss/pull/2392

**Review by gechiang — APPROVED** [review]
LGTM.

**Pull request merged**
