### PR TITLE
Support for tc-dot1p and tc-dscp qosmap

### PR DESCRIPTION
**Pull request by dmukun**
**What I did**

- Added support to configure TC-DOT1P qos map
- Added support to attach TC-DOT1P qos map to interface
- Added support to attach TC-DSCP qos map to interface
- Modified print strings in qos map handler functions

Note: All of the above are configured via json

**Why I did it**
Repo code does not contain support to configure TC-DOT1P qos map or support to attach TC-DSCP qos map to interface. There is partial support to configure TC-DSCP qos map

**How I verified it**
Sample configuration
```
{
"TC_TO_DOT1P_MAP": {
        "MAP1": {
            "0" : "3",
            "1" : "3",
            "2" : "1",
            "3" : "3",
            "4" : "4",
            "5" : "2",
            "6" : "1",
            "7" : "1"
        }
},
"TC_TO_DSCP_MAP": {
        "MAP1": {
            "0" : "3",
            "1" : "23",
            "2" : "11",
            "3" : "31",
            "4" : "44",
            "5" : "23",
            "6" : "19",
            "7" : "1"
        }
},

"PORT_QOS_MAP": {
        "Ethernet12": {
            "tc_to_dscp_map"  : "MAP1",
            "tc_to_dot1p_map"  : "MAP1"
         }
    }
}
```

1. Verified that L2 traffic with incoming dot1p priority is appropriatly remarked on outgoing interface (on which qos map is attached)
2. Verified that IP DSCP field is remarked appropriately as per configuration
3. Verified syslog, swss and sairedis.rec logs

**Details if related**
This commit has dependency on swss-common repo commit.
https://github.com/sonic-net/sonic-swss-common/pull/721

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ x] 202205

### CODE REVIEW

**Comment by dmukun** [comment]
Note that build failure is expected as this dependent on [this sonic-swss-common PR](https://github.com/sonic-net/sonic-swss-common/pull/721) which should be approved and merged first.

**Comment by prsunny** [comment]
@dmukun , please add unit tests to meet the coverage requirements

**Comment by prsunny** [comment]
@neethajohn , could you please review/signoff?

**Comment by dmukun** [comment]
@neethajohn Can you review this and enable commit, please?

**Comment by dmukun** [comment]
@neethajohn Can you complete this review, please?

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Sorry for the delay. The change looks good to me. Thanks for correction in the comments! @dmukun

**Comment by dmukun** [comment]
Thank you, @prsunny @bingwang-ms

**Pull request merged**
