### PR TITLE
Enhance getNeighborEntry to return neighbor entry for system neighbor

### PR DESCRIPTION
**Pull request by ysmanman**
**What I did**
Enhance getNeighborEntry to return neighbor entry for system neighbor

**Why I did it**
getNeighborEntry is not able to handle system neighbor today. This breaks features like Everflow in VOQ systems.

**How I verified it**
We verified the change by testing Everflow in VOQ system (e.g.,  mirror DIP is resolved to system neighbor).

**Details if related**

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@abdosi, can you take a look

**Comment by abdosi** [comment]
https://github.com/sonic-net/sonic-swss/pull/2392

**Comment by rlhui** [comment]
is this one still needed or can be closed?

**Comment by ysmanman** [comment]
> is this one still needed or can be closed?

Hi @rlhui, https://github.com/sonic-net/sonic-swss/pull/2392 should fix the same issue the PR addresses. I am closing it.

**Pull request closed without merging**
