### PR TITLE
[Orchagent] Add optional create_switch timeout parameter

### PR DESCRIPTION
**Pull request by rajkumar38**
Backport of PR #3258

**What I did**
Change adds optional create_switch timeout as command line parameter to orchagent.
**Why I did it**

**How I verified it**
Changes are verified to see passed timeout value is reflected only for create_switch api call from orchagent.
**Details if related**

### CODE REVIEW

**Comment by Blueve** [comment]
ADO: 29208990

**Review by Blueve — APPROVED** [review]

**Comment by prsunny** [comment]
@StormLiangMS , branch owner of 202311 for signoff

**Review by prsunny — APPROVED** [review]
lgtm, is the sonic-buildimage PR backported?

**Comment by Blueve** [comment]
Thank you @prsunny !
sonic-buildimage PR has backported: https://github.com/sonic-net/sonic-buildimage/pull/20347

And we need this PR merged and submodule updated in sonic-buildimage repo.

**Pull request merged**
