### PR TITLE
[muxorch] set mux state to init upon warm reboot

### PR DESCRIPTION
**Pull request by Ndancejic**
Warm reboot with manual mux mode was causing orchagent crash.

Initializing mux state to INIT upon warm reboot, the state will then be updated to reflect previous APPDB state.

**What I did**
Initialize mux state to INIT during warm reboot

**Why I did it**
 initializing mux state to Standby during warm reboot was causing orchagent to crash if mux was put in manual mode

**How I verified it**
 vstests included in PR

### CODE REVIEW

**Comment by Ndancejic** [comment]
responding to: https://github.com/sonic-net/sonic-swss/pull/2827#discussion_r1240477310
@vaibhavhd 

I added some active/standby states to test, but I'm not sure if mux flapping can be checked for here. My understanding is orchagent vstests test on a virtual device, so we're just testing orchagent logic here. I think for mux flapping check we need to make a sonic-mgmt test

**Comment by Ndancejic** [comment]
Looks like the build is gone so I can't check for this one. I'll rerun and see

**Review by prsunny — APPROVED** [review]
lgtm, @vaibhavhd to review

**Review by zjswhhh — APPROVED** [review]
lgtm

**Review by vaibhavhd — APPROVED** [review]

**Comment by zjswhhh** [comment]
Hi @Ndancejic  - can you please check the PR check failures?

**Comment by Ndancejic** [comment]
rebased changes onto master

**Comment by zjswhhh** [comment]
ADO#: 24645885

**Pull request merged**
