### PR TITLE
[202205] Use shared egress ACL table for PFCWD in BRCM DNX platform

### PR DESCRIPTION
**Pull request by ysmanman**
**What I did**
Backport https://github.com/sonic-net/sonic-swss/pull/3136 to 202205.

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by ysmanman** [comment]
Add @vmittal-msft @arlakshm @kenneth-arista for viz.

**Comment by prsunny** [comment]
I don't see the master PR even requested for backport to 202311/202305. Why is this need to be backported?

**Comment by ysmanman** [comment]
> I don't see the master PR even requested for backport to 202311/202305. Why is this need to be backported?

The PR is to fix P0 issue  https://github.com/sonic-net/sonic-buildimage/issues/17839.  According to @vmittal-msft, we were asked to fix this in 202205 too.

**Comment by vmittal-msft** [comment]
@ysmanman Can we list master PR here ? We usually open master PR first and then request for porting to another release.

**Comment by ysmanman** [comment]
> @ysmanman Can we list master PR here ? We usually open master PR first and then request for porting to another release.

This is the master PR https://github.com/sonic-net/sonic-swss/pull/3136.  I thought we agreed to create PR under 202205 directly to prioritize merging into 202205 in last week's chassis group meeting. Please check the note in thhttps://github.com/orgs/sonic-net/projects/3/views/5 for https://github.com/sonic-net/sonic-buildimage/issues/17839.

**Comment by arlakshm** [comment]
PR merge in master. This fix will not be backported to 202205. closing this PR

**Pull request closed without merging**
