### PR TITLE
[DASH] ACL tags implementation

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
**What I did**
Implement the DASH ACL tags feature according to [DASH ACL tags HLD](https://github.com/sonic-net/SONiC/blob/master/doc/dash/dash-acl-tags/dash-acl-tags.md)

**Why I did it**
To add support for DASH ACL tags feature

**How I verified it**
Run extended VS tests that cover new implementation

**Details if related**

### CODE REVIEW

**Comment by oleksandrivantsiv** [comment]
@prsunny kindly reminder.
Can you please review or assign someone to review the PR?

**Review by Pterosaur — COMMENTED** [review]
All changes look good to me.

@prsunny , But there is a concern that we store FULL ACL cache(groups, rules, and tags) in the memory of orchagent. Do you have any suggestions about this?

**Comment by prsunny** [comment]
> All changes look good to me.
> 
> @prsunny , But there is a concern that we store FULL ACL cache(groups, rules, and tags) in the memory of orchagent. Do you have any suggestions about this?

thats a good catch. We don't want to have cache for ACL rules, otherwise it will take high memory. @oleksandrivantsiv , could you please check on this and remove cache.

**Comment by oleksandrivantsiv** [comment]
> > All changes look good to me.
> > @prsunny , But there is a concern that we store FULL ACL cache(groups, rules, and tags) in the memory of orchagent. Do you have any suggestions about this?
> 
> thats a good catch. We don't want to have cache for ACL rules, otherwise it will take high memory. @oleksandrivantsiv , could you please check on this and remove cache.

@prsunny I have a plan to remove a cache in the separate PR by querying the information from APP DB directly. I suggest merging this PR to allow us to start working on the "E2E" flow testing.

**Comment by Pterosaur** [comment]
> > > All changes look good to me.
> > > @prsunny , But there is a concern that we store FULL ACL cache(groups, rules, and tags) in the memory of orchagent. Do you have any suggestions about this?
> > 
> > 
> > thats a good catch. We don't want to have cache for ACL rules, otherwise it will take high memory. @oleksandrivantsiv , could you please check on this and remove cache.
> 
> @prsunny I have a plan to remove a cache in the separate PR by querying the information from APP DB directly. I suggest merging this PR to allow us to start working on the "E2E" flow testing.

@oleksandrivantsiv Agree. Could you please update a commit: https://github.com/sonic-net/sonic-swss/commit/966c5bb051c13ce67ef5c961c292cb5a681e4db9 that is for fixing an ACL bug?

**Comment by oleksandrivantsiv** [comment]
> > > > All changes look good to me.
> > > > @prsunny , But there is a concern that we store FULL ACL cache(groups, rules, and tags) in the memory of orchagent. Do you have any suggestions about this?
> > > 
> > > 
> > > thats a good catch. We don't want to have cache for ACL rules, otherwise it will take high memory. @oleksandrivantsiv , could you please check on this and remove cache.
> > 
> > 
> > @prsunny I have a plan to remove a cache in the separate PR by querying the information from APP DB directly. I suggest merging this PR to allow us to start working on the "E2E" flow testing.
> 
> @oleksandrivantsiv Agree. Could you please update a commit: [966c5bb](https://github.com/sonic-net/sonic-swss/commit/966c5bb051c13ce67ef5c961c292cb5a681e4db9) that is for fixing an ACL bug?

@Pterosaur I updated the branch to include the changes form [966c5bb](https://github.com/sonic-net/sonic-swss/commit/966c5bb051c13ce67ef5c961c292cb5a681e4db9) commit.

**Comment by oleksandrivantsiv** [comment]
@prsunny, @Pterosaur if there are no other comments can you please approve the PR?

**Review by Pterosaur — APPROVED** [review]

**Review by Yakiv-Huryk — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
