### PR TITLE
[sai_failure_dump]Invoking dump during SAI failure

### PR DESCRIPTION
**Pull request by dgsudharsan**
HLD: https://github.com/sonic-net/SONiC/pull/1212
Depends on https://github.com/sonic-net/sonic-sairedis/pull/1198
**What I did**
Added logic to invoke SAI failure dump during any SAI programming failure before invoking abort.

**Why I did it**
To collect necessary dumps in problem state in syncd before abort is called and all processes restarts

**How I verified it**
Manual verification. Added UT to cover abort scenario as well.

**Details if related**

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@prsunny  I have added tests to cover all lines  except main file (which cannot be included) but still the coverage throws error. I feel there is some issue with coverage here. Can you please help?

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
Tests are added for coverage but for some reason, it is not showing in the tool. Skipping the check as the changes are in the failure path.

**Comment by yxieca** [comment]
@dgsudharsan please help create a separate PR for 202205 branch.

**Comment by dgsudharsan** [comment]
@yxieca I already created and its merged https://github.com/sonic-net/sonic-swss/pull/2661. Can you please update submodule?

**Pull request merged**
