### PR TITLE
[orchdaemon]: Fixed sairedis record file rotation

### PR DESCRIPTION
**Pull request by bacrossland**
**What I did**
Fix Azure/sonic-buildimage[#8162](https://github.com/Azure/sonic-buildimage/issues/8162)

Moved sairedis record file rotation logic out of flush() to fix issue.

**Why I did it**
Sairedis record file was not releasing the file handle on rotation. This is because the file handle release was inside the flush() which was only being called if a select timeout was triggered. Moved the logic to its own function which is called in the start() loop.

**How I verified it**
Ran a script to fill log and verified that rotation was happening correctly.

Signed-off-by: Bryan Crossland [bryan.crossland@target.com](mailto:bryan.crossland@target.com)

### CODE REVIEW

**Comment by lguohan** [comment]
@kcudnik , can you review this?

**Review by kcudnik — DISMISSED** [review]

**Comment by kcudnik** [comment]
Please take a look at this PR too: https://github.com/Azure/sonic-sairedis/pull/1058

**Comment by Blueve** [comment]
@bacrossland Build has passed. Could you add UT for your change?
https://dev.azure.com/mssonic/build/_build/results?buildId=121405&view=codecoverage-tab

**Comment by bacrossland** [comment]
Thank you @Blueve. I will get that unit test added.

**Comment by Blueve** [comment]
@kcudnik  The UT coverage for this repo might not accurate now and most PR are not having UT. Do you think we can merge this PR wo/ UT?

**Comment by kcudnik** [comment]
no, please add corresponding tests to fix code coverage, we dont want to skip this, threshold must be met

**Comment by bacrossland** [comment]
@kcudnik I'm setting aside time next week to fix this PR and get the testing in.

**Comment by kcudnik** [comment]
sure, lets fix this this week

**Review by kcudnik — DISMISSED** [review]

**Comment by bacrossland** [comment]
I've gotten a test to run locally and checked that in for code coverage. This branch is out of date with master. I will be updating that today.

**Comment by bacrossland** [comment]
Merged in master.

**Comment by bacrossland** [comment]
The LGTM analysis is failing on this:
```
[2022-10-01 09:09:02] [build-stderr] In file included from defaultvalueprovider.cpp:10:
[2022-10-01 09:09:02] [build-stderr] defaultvalueprovider.h:8:10: fatal error: libyang/libyang.h: No such file or directory
[2022-10-01 09:09:02] [build-stderr]     8 | #include <libyang/libyang.h>
[2022-10-01 09:09:02] [build-stderr]       |          ^~~~~~~~~~~~~~~~~~~
[2022-10-01 09:09:02] [build-stderr] compilation terminated.
[2022-10-01 09:09:02] [build-stderr] make[3]: *** [Makefile:787: libswsscommon_la-defaultvalueprovider.lo] Error 1
[2022-10-01 09:09:02] [build-stderr] make[3]: *** Waiting for unfinished jobs....
[2022-10-01 09:09:06] [build-stdout] make[3]: Leaving directory '/opt/src/sonic-swss-common/common'
[2022-10-01 09:09:06] [build-stderr] make[2]: *** [Makefile:440: all-recursive] Error 1
[2022-10-01 09:09:06] [build-stdout] make[2]: Leaving directory '/opt/src/sonic-swss-common'
[2022-10-01 09:09:06] [build-stderr] make[1]: *** [Makefile:372: all] Error 2
[2022-10-01 09:09:06] [build-stdout] make[1]: Leaving directory '/opt/src/sonic-swss-common'
[2022-10-01 09:09:06] [build-stderr] dh_auto_build: error: make -j4 returned exit code 2
[2022-10-01 09:09:06] [build-stderr] make: *** [debian/rules:33: build] Error 25
[2022-10-01 09:09:06] [build-stderr] dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
[2022-10-01 09:09:06] [ERROR] Spawned process exited abnormally (code 2; tried to run: [/opt/work/lgtm-workspace/lgtm/extract.sh])
A fatal error occurred: Exit status 2 from command: [/opt/work/lgtm-workspace/lgtm/extract.sh]
```

**Comment by bacrossland** [comment]
Pulled in latest commits that have fixes for missing libyang

**Comment by bacrossland** [comment]
@kcudnik @Blueve @prsunny Everything is passing. Ready for a review and a merge.

**Review by kcudnik — APPROVED** [review]

**Comment by yxieca** [comment]
@bacrossland can you raise a separate PR for 202205 branch? This change cannot be cherry-picked to 202205 branch cleanly.

**Comment by bacrossland** [comment]
Sure. I'll put those in later tonight or tomorrow morning.

**Comment by bacrossland** [comment]
PR 202205 Release: https://github.com/sonic-net/sonic-swss/pull/2480

**Comment by bacrossland** [comment]
@qiluo-msft 202012 is going to take more work as that release is missing things I relied on for the unit tests I put in master. I have to rework my unit tests to make it work for that old release. I could also just put in a PR without the unit tests but that would be less desirable.

**Comment by bacrossland** [comment]
PR 202012 Release: https://github.com/sonic-net/sonic-swss/pull/2481

**Comment by liuh-80** [comment]
202012 branch PR merged: https://github.com/sonic-net/sonic-swss/pull/2481

**Pull request merged**
