### PR TITLE
[202305][ppi]: Implement port bulk comparison logic

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**DEPENDS:**
1. https://github.com/sonic-net/sonic-sairedis/pull/1171
2. https://github.com/sonic-net/sonic-sairedis/pull/1197
3. https://github.com/sonic-net/sonic-swss/pull/2806

**HLD:** https://github.com/sonic-net/SONiC/pull/1084

**What I did**
* Implemented port bulk add/remove comparison logic
* Refactored Port OA to facilitate port config operations

**Why I did it**
* To improve switch Fast Boot startup time

**How I verified it**
* UT tests
* VS tests

**Details if related**
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2564

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by nazariig** [comment]
@StormLiangMS / @prsunny can you please help to merge?

**Comment by prsunny** [comment]
@prgeor, is this approved for 202305? If so, please signoff and @StormLiangMS can merge

**Comment by StormLiangMS** [comment]
This one is a new feature and get merged to master after 202305 branch out, would not pick up for 202305 and old ones, unless enough justification.

@prsunny @prgeor @nazariig

**Comment by liat-grozovik** [comment]
@StormLiangMS  this is not correct. the entire feature is already in 202305 but this last one. it is already on 202211_1
this is not a new feature, this is a must feature that was not fully cherrypicked.

please take it to 202305

**Comment by StormLiangMS** [comment]
@liat-grozovik got it, could I ask a full regress test with 202305 for this PR? Pls update the test result in the PR. @nazariig

**Comment by StormLiangMS** [comment]
must to have for fast reboot, cherry pick to 202305.

**Pull request merged**
