### PR TITLE
[202211]Custom monitoring based priority tunnels

### PR DESCRIPTION
**Pull request by siqbal1986**
This PR implements the Vxlan ECMP priority tunnels where route next hop groups are switched based on the state of the next hop monitor session and their priority. This implementation allows primary and secondary next-hop groups which are switched based on the monitor state of the next hops. Please see the included tests to see what this code would do for detail.

cherry-pick  https://github.com/sonic-net/sonic-swss/pull/2719

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by prsunny — APPROVED** [review]
lgtm

**Comment by siqbal1986** [comment]
it seems, this PR requires https://github.com/sonic-net/sonic-swss-common/pull/725  CP to 202211. Requested initiated for CP. ill merge this once that request is completed.

**Comment by siqbal1986** [comment]
Cannot merge until https://github.com/sonic-net/sonic-swss-common/pull/725 cast to 202211 goes in. otherwise it will cause build failure in the branch.

**Pull request closed without merging**
