### PR TITLE
[acl] Add new ACL key BTH_OPCODE and AETH_SYNDROME 

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
YANG model PR: https://github.com/sonic-net/sonic-buildimage/pull/13340

**What I did**

Add new ACL key BTH_OPCODE and AETH_SYNDROME 

**Why I did it**

Add new ACL key BTH_OPCODE and AETH_SYNDROME 

**How I verified it**

Manual test

**Details if related**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
@stepanblyschak, could you please review it?

**Review by stepanblyschak — DISMISSED** [review]

**Review by prsunny — APPROVED** [review]
lgtm

**Review by keboliu — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @prsunny , could you please help merge this?

**Pull request merged**
