### PR TITLE
Reduce log verbosity when the capability is not implemented

### PR DESCRIPTION
**Pull request by vivekrnv**
**Why I did**

SAI_SWITCH_ATTR_SUPPORTED_OBJECT_TYPE_LIST is not a mandatory attribute and is not supported in some platforms. 

There is an error log seen for such platforms. Reduce noise by changing the verbosity to INFO. 

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by oleksandrivantsiv — APPROVED** [review]

**Comment by vivekrnv** [comment]
@cscarpitta @prsunny Please review

**Review by cscarpitta — APPROVED** [review]
LGTM

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@bingwang-ms Can you please help to cherry-pick this fix to 202405?

**Comment by bingwang-ms** [comment]
@prsunny FYI

**Pull request merged**
