### PR TITLE
[Buffer orch] Fix maximum headroom check failure in cold reboot

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**

Fix maximum headroom check failure in the cold reboot.
The accumulative headroom on a port should be compared with the maximum headroom supported on the port whenever a buffer priority group is created/updated in the dynamic buffer model which depends on the maximum headroom being exposed to the STATE_DB during orchagent initialization.
However, in the cold reboot, orchagent starts slow which prevents the threshold from being exposed on time. In this case, the buffer manager is not able to perform the headroom check and the buffer orchagent should handle the possible failure from SAI in case the accumulative headroom exceeds the threshold.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**Why I did it**

To fix the issue.

**How I verified it**

Manually/regression test.

**Details if related**

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by prsunny** [comment]
@stephenxs , @dgsudharsan , if it failed, how does it recover?

**Comment by stephenxs** [comment]
Hi
This is caused by wrong user configuration.
User should correct the configuration if it fails

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Prince Sunny ***@***.***>
发送时间: 星期三, 十一月 8, 2023 8:25 上午
收件人: sonic-net/sonic-swss ***@***.***>
抄送: Stephen Sun ***@***.***>; Mention ***@***.***>
主题: Re: [sonic-net/sonic-swss] [Buffer orch] Fix maximum headroom check failure in cold reboot (PR #2948)


@stephenxs<https://github.com/stephenxs> , @dgsudharsan<https://github.com/dgsudharsan> , if it failed, how does it recover?

―

**Comment by prsunny** [comment]
> Hi This is caused by wrong user configuration. User should correct the configuration if it fails

It doesn't align with this description "The accumulative headroom on a port is compared with the maximum headroom supported on the port whenever a buffer priority group is created/updated in the dynamic buffer model which depends on the maximum headroom being exposed to the STATE_DB during orchagent initialization."

**Comment by stephenxs** [comment]
Hi
In the 2nd paragraph I mentioned the exception.
To avoid the confusion I will rephrase it as "The accumulative headroom on a port should be compared with the maximum headroom supported on the port whenever a buffer priority group is created/updated in the dynamic buffer model which depends on the maximum headroom being exposed to the STATE_DB during orchagent initialization."

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Prince Sunny ***@***.***>
发送时间: 星期三, 十一月 8, 2023 9:34 上午
收件人: sonic-net/sonic-swss ***@***.***>
抄送: Stephen Sun ***@***.***>; Mention ***@***.***>
主题: Re: [sonic-net/sonic-swss] [Buffer orch] Fix maximum headroom check failure in cold reboot (PR #2948)


Hi This is caused by wrong user configuration. User should correct the configuration if it fails

It doesn't align with this description "The accumulative headroom on a port is compared with the maximum headroom supported on the port whenever a buffer priority group is created/updated in the dynamic buffer model which depends on the maximum headroom being exposed to the STATE_DB during orchagent initialization."

―

**Comment by liat-grozovik** [comment]
@prsunny any further comments?

**Comment by prsunny** [comment]
> @prsunny any further comments?

From what I understand, it is not a common scenario (like manually editing a config_db.json) to simulate this failure. So this handling, imo is unnecessary.

**Comment by stephenxs** [comment]
> > @prsunny any further comments?
> 
> From what I understand, it is not a common scenario (like manually editing a config_db.json) to simulate this failure. So this handling, imo is unnecessary.

Hi @prsunny 
It is one scenario that a customer manually modifies the config_db.json and reboot the switch.
There is another scenario.
A customer manually configured a very long cable length. The buffer manager denies the configuration but it can not remove it from the config db. Once the user saves configuration and reboots the switch, the failure will happen.

**Comment by dgsudharsan** [comment]
Verified on top of 202305 commit https://github.com/sonic-net/sonic-buildimage/commit/a3f81537b3380df58346bdb995820330280ed00f

**Comment by stephenxs** [comment]
> @stephenxs cherry pick PR didn't pass PR checker. Please check!!!#3001

It no longer needs to cherry-pick to 202205. Just removed the flag.
Thanks

**Pull request merged**
