### PR TITLE
Remove fabric queue counters.

### PR DESCRIPTION
**Pull request by jfeng-arista**
**What I did**
Remove fabric queue counters. 

**Why I did it**
This is fixing issue #15586. Where the following messages are seen 

NOTICE syncd0#syncd: :- setQueueCounterList: FABRIC_QUEUE_STAT_COUNTER: queue oid:0x18d051500000001 does not has supported counters

Based on  case CS00012300922, the support of these queue counters objects are removed after 9.x for DNX. 

**How I verified it**

Manually tested an image with the fix on a system that has J2c+ linecards, and do not see the error messages. 

**Details if related**

### CODE REVIEW

**Comment by kenneth-arista** [comment]
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/15586

**Review by arlakshm — APPROVED** [review]

**Comment by jfeng-arista** [comment]
what is the functional implication of this change ? -- the show fabric counters queue command will display 0 values in some field.

**Comment by rlhui** [comment]
@arlakshm , would you please help create an MSFT ADO for this, thanks

**Comment by gechiang** [comment]
@rlhui , @arlakshm ,
In the interest of time I have created the needed MSFT ADO: 24917858

@yxieca , @StormLiangMS , Please help cherry-pick backport this fix to corresponding release branch, Thanks!

**Comment by gechiang** [comment]
@arlakshm , @abdosi , @tjchadaga , @jfeng-arista 
Since this issue is only present on SAI 9.x and above, 202205 SAI is at SAI 7.x So this PR probably is not needed for 202205 release and only needed for Master, 202305 and later releases, correct?

**Comment by gechiang** [comment]
> @arlakshm , @abdosi , @tjchadaga , @jfeng-arista Since this issue is only present on SAI 9.x and above, 202205 SAI is at SAI 7.x So this PR probably is not needed for 202205 release and only needed for Master, 202305 and later releases, correct?

Confirmed with Arvind over the phone and saw in the issue mentioned that this is required for 202205 because when BRCM removed the support in 9.X they also went back and removed it from 7.X so we do see this same issue on 202205 and require this fix be backported to 202205.
I will also go ahead add this for 202211 and 202305 as well...

**Comment by jfeng-arista** [comment]
> @arlakshm , @abdosi , @tjchadaga , @jfeng-arista Since this issue is only present on SAI 9.x and above, 202205 SAI is at SAI 7.x So this PR probably is not needed for 202205 release and only needed for Master, 202305 and later releases, correct?

I remember to see the issue message on 202205 image and I think we may need this into 202205

**Comment by gechiang** [comment]
> > @arlakshm , @abdosi , @tjchadaga , @jfeng-arista Since this issue is only present on SAI 9.x and above, 202205 SAI is at SAI 7.x So this PR probably is not needed for 202205 release and only needed for Master, 202305 and later releases, correct?
> 
> I remember to see the issue message on 202205 image and I think we may need this into 202205

Yes. I have looked into the original issue filed for this and it is stated clearly there that when BRCM removed it from the latest, they also removed the change from SAI 7.x that is being used by 202205 so this bug fux is needed for 202205 branch.

**Comment by StormLiangMS** [comment]
@jfeng-arista  202305 conflict, could you help to file separate PR for 202305?

@gechiang  for vis.

**Comment by jfeng-arista** [comment]
> @jfeng-arista 202305 conflict, could you help to file separate PR for 202305?
> 
> @gechiang for vis.

ok, please let me know the repo, I can raise a separate one

**Comment by gechiang** [comment]
> > @jfeng-arista 202305 conflict, could you help to file separate PR for 202305?
> > @gechiang for vis.
> 
> ok, please let me know the repo, I can raise a separate one

https://github.com/sonic-net/sonic-swss/tree/202305

**Comment by gechiang** [comment]
@jfeng-arista Just a reminder to raise PRs to both 202305 and 202211 branches. Thanks!

**Comment by jfeng-arista** [comment]
> @jfeng-arista Just a reminder to raise PRs to both 202305 and 202211 branches. Thanks!

sure , will do

**Comment by jfeng-arista** [comment]
sorry about the late, in 202305 and 202211 ,orchagent does not have this enabled :
orchDaemon->setFabricQueueStatEnabled(false);
, so no need for this PR.

**Comment by gechiang** [comment]
> sorry about the late, in 202305 and 202211 ,orchagent does not have this enabled : orchDaemon->setFabricQueueStatEnabled(false); , so no need for this PR.

Thanks for the clarification on the backport branch.
I have removed the request for the 202305 and 202211 back port.

**Comment by jfeng-arista** [comment]
> > sorry about the late, in 202305 and 202211 ,orchagent does not have this enabled : orchDaemon->setFabricQueueStatEnabled(false); , so no need for this PR.
> 
> Thanks for the clarification on the backport branch. I have removed the request for the 202305 and 202211 back port.

thank you

**Pull request merged**
