### PR TITLE
[dash] Do not use an action drop with the inbound routing table.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
**What I did**
Do not use an action drop with the inbound routing table.

**Why I did it**
Action "drop" is not supported by the inbound routing table. SAI_INBOUND_ROUTING_ENTRY_ACTION_DENY action is no longer available in SAI v1.12

**How I verified it**
Run sonic-mgmt DASH VNET to VNET test.

**Details if related**

### CODE REVIEW

**Review by prabhataravind — APPROVED** [review]

**Comment by prsunny** [comment]
@oleksandrivantsiv , can you help check failure?

**Comment by oleksandrivantsiv** [comment]
> @oleksandrivantsiv , can you help check failure?

@prsunny  it is an infrastructure issue. It fails on an attempt to install dependencies.

**Pull request merged**
