### PR TITLE
[fpm] Fix FpmLink to read all netlink messages from FPM message

### PR DESCRIPTION
**Pull request by stepanblyschak**
In case of using ```dplane_fpm_nl``` zebra plugin we receive RTM_DELROUTE followed by RTM_NEWROUTE in a single FPM message when route attributes change (i.e nexthops change). Current implementation can only read the first one and ignores the rest.

**What I did**

I fixed FPM implementation to read multiple nl messages in a single FPM message.

**Why I did it**

Trying to move towards using ```dplane_fpm_nl```.

**How I verified it**

UT and using ```dplane_fpm_nl``` zebra plugin.

**Details if related**

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@StormLiangMS kindly reminder to review and merge

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
