### PR TITLE
[tests] mark suppress-fib-pending VS test as expected to fail

### PR DESCRIPTION
**Pull request by stepanblyschak**
**What I did**

Revert suppress FIB pending feature

**Why I did it**

Some unresolved FRR issues in current version

**How I verified it**

Build and run

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
I don't think we need to revert swss changes.

**Comment by stepanblyschak** [comment]
@prsunny In theory yes, we could keep it. However, please note, as part of this PR I revert a VS test that will not work without FRR config. Reverting just a VS test means I remove the coverage for suppress FIB code.

**Comment by prsunny** [comment]
may be we can mark the test skipped for now and create an issue to track.

**Comment by stepanblyschak** [comment]
@prsunny Update PR to just mark the test as x(pected)fail. It was already marked that way to solve a cyclic dependency between sonic-buildimage and sonic-swss changes at that time and forgotten to be removed, now, I just updated the reason message.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
