### PR TITLE
Upstream new development on p4orch

### PR DESCRIPTION
**Pull request by mint570**
Upstream new development on p4orch:
1. New actions in route manager: trap, set metadata.
2. New match attribute in ACL manager: ROUTE_DST_USER_META.
3. Bulk SAI call in route manager.
4. Added l3 admin manager.
5. Added GRE tunnel manager.
6. P4orch state verification for internal cache and ASIC DB (place holder).
7. Bug fixes and code enhancements.

Co-authored-by: Runming Wu [runmingwu@google.com](mailto:runmingwu@google.com)
Co-authored-by: Yilan Ji [yilanji@google.com](mailto:yilanji@google.com)
Co-authored-by: Jaffar Abdul [jabdulabdul@google.com](mailto:jabdulabdul@google.com)

### CODE REVIEW

**Comment by mint570** [comment]
New definitions are merged in https://github.com/Azure/sonic-swss-common/pull/604.
But the test still not picking up the new change.

**Comment by mint570** [comment]
@prsunny 
Can you please take a look?

**Comment by mint570** [comment]
@prsunny
Can you please take a look at this pr?

We have an internal fix for https://github.com/Azure/sonic-buildimage/issues/10410. Would like to upstream our fix after this pr.

**Comment by mint570** [comment]
The last few of the pytests failed. The number of failed tests are different each time. But they are at the end of the run.
I suspect there are some memory or dish space run out.
For now, I just disabled a few tests at the end.

**Comment by mint570** [comment]
All runs passed now except for the coverage.
I disabled a few pytest at the end due to the memory/disk (probabiliry) issue.
We plan to enable the p4orch unit test run in the future, which will provide good p4orch coverage.

**Comment by mint570** [comment]
@prsunny 
With p4orch unit test enabled and code coverage enabled, this PR is fully ready now.
Please take a look.

**Review by prsunny — APPROVED** [review]
switchorch changes lgtm

**Comment by prsunny** [comment]
@bhagatyj to signoff

**Comment by bhagatyj** [comment]
lgtm.

**Pull request merged**
