### PR TITLE
[EVPN]Fixing nexthop group delete when multiple routes point to the nexthop group

### PR DESCRIPTION
**Pull request by dgsudharsan**
**What I did**
When multiple routes point to a nexthop group which means the ref count of ngh is more than one, there is an error condition in the removal flow. The original logic is to remove nhg only when ref count becomes zero. However due to the structuring of if else statements, if the nhg count is not zero, the logic fallbacks to removeOverlayNextHops which will also get added to the list of tasks.
Later when bulker logic kicks in, the nexthop group removal will remove the nexthops associated. However the removeOverlayNextHops  will also subsequently try to remove the same nexthops resulting in errors below.

```
Apr 19 11:51:05.323909 anc-ali-t9 NOTICE swss#orchagent: :- removeRoutePost: Remove overlay Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc,173.108.108.2@vniVlan30@30@c2:72:8d:aa:61:d2
Apr 19 11:51:05.323976 anc-ali-t9 NOTICE swss#orchagent: :- removeRoutePost: Remove overlay Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc
Apr 19 11:51:05.328042 anc-ali-t9 NOTICE swss#orchagent: :- removeOverlayNextHops: Remove overlay Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc
Apr 19 11:51:05.328081 anc-ali-t9 NOTICE swss#orchagent: :- removeNextHopGroup: Delete next hop group 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc,173.108.108.2@vniVlan30@30@c2:72:8d:aa:61:d2
Apr 19 11:51:05.329642 anc-ali-t9 NOTICE syncd#SDK: [SAI_NEXT_HOP_GROUP.NOTICE] mlnx_sai_nexthopgroup.c[951]- mlnx_remove_next_hop_group: Remove next hop group next hop group id 0x000000C8
Apr 19 11:51:05.330400 anc-ali-t9 NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for vtep1, ip 173.106.106.2, mac b6:a1:0b:0b:d3:cc, vni 30
Apr 19 11:51:05.330658 anc-ali-t9 NOTICE syncd#SDK: [SAI_NEXT_HOP.NOTICE] mlnx_sai_nexthop.c[1431]- mlnx_remove_next_hop: Remove next hop next hop id 326, ext 1
Apr 19 11:51:05.331108 anc-ali-t9 NOTICE swss#orchagent: :- removeTunnelNextHop: Removed Tunnel next hop vtep1, 173.106.106.2@30@b6:a1:0b:0b:d3:cc
Apr 19 11:51:05.331877 anc-ali-t9 NOTICE swss#orchagent: :- removeOverlayNextHops: Remove overlay Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc,173.108.108.2@vniVlan30@30@c2:72:8d:aa:61:d2
Apr 19 11:51:05.331877 anc-ali-t9 NOTICE swss#orchagent: :- removeOverlayNextHops: Remove overlay Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc,173.108.108.2@vniVlan30@30@c2:72:8d:aa:61:d2
Apr 19 11:51:05.331877 anc-ali-t9 NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for vtep1, ip 173.106.106.2, mac b6:a1:0b:0b:d3:cc, vni 30
Apr 19 11:51:05.331877 anc-ali-t9 ERR swss#orchagent: :- removeTunnelNextHop: Failed to remove Tunnel next hop vtep1, 173.106.106.2@30@b6:a1:0b:0b:d3:cc
Apr 19 11:51:05.331877 anc-ali-t9 ERR swss#orchagent: :- removeOverlayNextHops: Tunnel Nexthop 173.106.106.2@vniVlan30@30@b6:a1:0b:0b:d3:cc,173.108.108.2@vniVlan30@30@c2:72:8d:aa:61:d2 delete failed
```

Fixed a second scenario where a nexthop is part of NHG as well as functioning as individual nexthop to a route. Lets assume NH1 is part of NHG and R1 is pointing to NH1 and R2 is pointing to NH2. 
When both R1 and R2 are deleted,  NH1 delete comes first which reduces ref count of NH1 and adds it to m_bulkNhgReducedRefCnt. Later NHG comes and its added to m_bulkNhgReducedRefCnt.

However when m_bulkNhgReducedRefCnt is later processed, NHG delete is processed first which checks for NH1 ref count after removing NHG and finds it zero (since it was removed even before adding to m_bulkNhgReducedRefCnt). This removes the NH1 as part of NHG removal. Later when NH1 removal is processed while iterating through  m_bulkNhgReducedRefCnt  it leads to error.
```
Apr 24 15:33:35.313676 anc-ali-t11 NOTICE swss#orchagent: :- removeRoutePost: Remove overlay Nexthop 173.116.116.2@vniVlan27@27@da:d0:2e:40:6d:ba
Apr 24 15:33:35.315774 anc-ali-t11 NOTICE swss#orchagent: :- removeNextHopGroup: Delete next hop group 173.108.108.2@vniVlan27@27@7a:1e:b3:02:cd:55,173.116.116.2@vniVlan27@27@da:d0:2e:40:6d:ba
Apr 24 15:33:35.317500 anc-ali-t11 NOTICE syncd#SDK: [SAI_NEXT_HOP_GROUP.NOTICE] mlnx_sai_nexthopgroup.c[951]- mlnx_remove_next_hop_group: Remove next hop group next hop group id 0x00000048
Apr 24 15:33:35.318345 anc-ali-t11 NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for vtep1, ip 173.108.108.2, mac 7a:1e:b3:02:cd:55, vni 27
Apr 24 15:33:35.318646 anc-ali-t11 NOTICE syncd#SDK: [SAI_NEXT_HOP.NOTICE] mlnx_sai_nexthop.c[1431]- mlnx_remove_next_hop: Remove next hop next hop id 3782, ext 1
Apr 24 15:33:35.319188 anc-ali-t11 NOTICE swss#orchagent: :- removeTunnelNextHop: Removed Tunnel next hop vtep1, 173.108.108.2@27@7a:1e:b3:02:cd:55
Apr 24 15:33:35.319188 anc-ali-t11 NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for vtep1, ip 173.116.116.2, mac da:d0:2e:40:6d:ba, vni 27
Apr 24 15:33:35.319491 anc-ali-t11 NOTICE syncd#SDK: [SAI_NEXT_HOP.NOTICE] mlnx_sai_nexthop.c[1431]- mlnx_remove_next_hop: Remove next hop next hop id 6918, ext 1
Apr 24 15:33:35.320017 anc-ali-t11 NOTICE swss#orchagent: :- removeTunnelNextHop: Removed Tunnel next hop vtep1, 173.116.116.2@27@da:d0:2e:40:6d:ba
Apr 24 15:33:35.320847 anc-ali-t11 NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for vtep1, ip 173.116.116.2, mac da:d0:2e:40:6d:ba, vni 27
Apr 24 15:33:35.320847 anc-ali-t11 ERR swss#orchagent: :- removeTunnelNextHop: Failed to remove Tunnel next hop vtep1, 173.116.116.2@27@da:d0:2e:40:6d:ba
Apr 24 15:33:35.320847 anc-ali-t11 ERR swss#orchagent: :- removeOverlayNextHops: Tunnel Nexthop 173.116.116.2@vniVlan27@27@da:d0:2e:40:6d:ba delete failed

```

The fix is to add NH to m_bulkNhgReducedRefCnt only when ref count becomes zero.

**Why I did it**
To fix proper handling of ECMP pointed by multiple routes.

**How I verified it**
Added VS tests to verify.

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@Ndancejic for viz

**Review by marian-pritsak — APPROVED** [review]

**Review by utpalkantpintoo — APPROVED** [review]

**Pull request merged**
