### PR TITLE
Disable `arp_evict_nocarrier` for vlan host intf 

### PR DESCRIPTION
**Pull request by lolyu**
**What I did**
Cherry-pick back https://github.com/sonic-net/sonic-swss/pull/2469 into 202205.

**Why I did it**
It is reverted in 202205: https://github.com/sonic-net/sonic-swss/pull/2518 because of the flakiness of `test_vlan.py`

**How I verified it**
This depends on the following PRs:
https://github.com/sonic-net/sonic-swss/pull/2504
https://github.com/sonic-net/sonic-swss/pull/2541

**Details if related**

### CODE REVIEW

**Comment by yxieca** [comment]
@lolyu can you check the vstest failure?

**Review by prsunny — APPROVED** [review]

**Pull request closed without merging**
