### PR TITLE
[orchagent][202305]: admin-disable port before setPortSerdesAttribute()

### PR DESCRIPTION
**Pull request by amnsinghal**
Double-commit [#2831](https://github.com/sonic-net/sonic-swss/pull/2831) from master.

**What I did**
Admin-disable port before applying media-based NPU serdes attributes from [media_settings.json](https://github.com/sonic-net/SONiC/blob/master/doc/media-settings/Media-based-Port-settings.md).

**Why I did it**
This fix is needed along with xcvrd changes https://github.com/sonic-net/sonic-platform-daemons/pull/377.
Maintain deterministic behavior of [interface bring-up](https://github.com/sonic-net/SONiC/blob/master/doc/sfp-cmis/Interface-Link-bring-up-sequence.md), by toggling host_tx_ready flag, which will trigger CMIS reinit for the module once NPU serdes params have been applied.

**How I verified it**
Added mock-test for portsorch.cpp

### CODE REVIEW

**Comment by amnsinghal** [comment]
@prsunny @StormLiangMS @prgeor Can you pls check CodeQL failure, doesn't look related to my changes. This is double-commit of  https://github.com/sonic-net/sonic-swss/pull/2831 from master, thanks.

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@StormLiangMS please mege to 202305. The CodeQL failure is not related to this PR

**Comment by amnsinghal** [comment]
@StormLiangMS @prgeor Can you pls merge this, if no further comments. Thanks!

**Comment by amnsinghal** [comment]
@StormLiangMS @prgeor Can you pls merge this, if no further comments. Thanks!

**Comment by StormLiangMS** [comment]
@amnsinghal pls check the build failure. 

21s
Run cd ..
Cloning into 'sonic-sairedis'...
Submodule 'SAI' (https://github.com/opencomputeproject/SAI.git) registered for path 'SAI'
Cloning into '/home/runner/work/sonic-swss/sonic-sairedis/SAI'...
Submodule path 'SAI': checked out '[1](https://github.com/sonic-net/sonic-swss/actions/runs/6101542799/job/16775630692?pr=2895#step:7:1)761e2f721ecc5295898b457465cf3abc3adaf96'
Submodule 'bm/behavioral-model' (https://github.com/p4lang/behavioral-model.git) registered for path 'SAI/bm/behavioral-model'
Submodule 'test/ptf' (https://github.com/p4lang/ptf) registered for path 'SAI/test/ptf'
Submodule 'test/saithrift/ctypesgen' (https://github.com/davidjamesca/ctypesgen) registered for path 'SAI/test/saithrift/ctypesgen'
Cloning into '/home/runner/work/sonic-swss/sonic-sairedis/SAI/bm/behavioral-model'...
Cloning into '/home/runner/work/sonic-swss/sonic-sairedis/SAI/test/ptf'...
Cloning into '/home/runner/work/sonic-swss/sonic-sairedis/SAI/test/saithrift/ctypesgen'...
Submodule path 'SAI/bm/behavioral-model': checked out '55b2b04fb3dbeb27621[42](https://github.com/sonic-net/sonic-swss/actions/runs/6101542799/job/16775630692?pr=2895#step:7:43)db73627f3918f7bf7f2'
Submodule path 'SAI/test/ptf': checked out '749[43](https://github.com/sonic-net/sonic-swss/actions/runs/6101542799/job/16775630692?pr=2895#step:7:44)66607e2e4c171439df3585eba3c9769fad8'
Submodule path 'SAI/test/saithrift/ctypesgen': checked out '3d2d9803339503d2988382aa861b47a6a4872c32'
~/work/sonic-swss/sonic-sairedis ~/work/sonic-swss
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:9: installing 'config/compile'
configure.ac:11: installing 'config/config.guess'
configure.ac:11: installing 'config/config.sub'
configure.ac:6: installing 'config/install-sh'
configure.ac:6: installing 'config/missing'
lib/Makefile.am: installing 'config/depcomp'
pyext/py2/Makefile.am:4: installing 'config/py-compile'
dh binary-syncd-vs
dh: error: Unknown sequence binary-syncd-vs (choose from: binary binary-arch binary-indep build build-arch build-indep clean install install-arch install-indep)
make: *** [debian/rules:[46](https://github.com/sonic-net/sonic-swss/actions/runs/6101542799/job/16775630692?pr=2895#step:7:47): binary-syncd-vs] Error 25
Error: Process completed with exit code 2

**Comment by StormLiangMS** [comment]
@prgeor  build check failed, need to fix.

**Comment by amnsinghal** [comment]
@StormLiangMS Prince George commented last week that the CodeQL failure is not related to this PR, Azure build and tests have all passed.

**Comment by amnsinghal** [comment]
@prgeor @StormLiangMS Can you pls check these build failures after upgrading to latest 202305, doesn't look related to my changes, any known issues?

```
make[4]: *** No rule to make target '../../lib/recorder.cpp', needed by 'tests_teammgrd-recorder.o'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/__w/1/s/tests/mock_tests'
make[3]: *** [Makefile:725: all-recursive] Error 1
make[3]: Leaving directory '/__w/1/s/tests'
```

**Comment by StormLiangMS** [comment]
@amnsinghal build passed, failed at UT, could you help to take a look?

test_sub_port_intf_nhg_accel failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	Unexpected number of keys: expected=6, received=4 (('oid:0x2d0000000007f3', 'oid:0x2d0000000007f4', 'oid:0x2d0000000007f2', 'oid:0x2d0000000007f5')), table="ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER"
	[<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1468>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1410>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:395>]
test_sub_port_intf_nhg_accel failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	Expected field/value pairs not found: expected={'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_GROUP_ID': 'oid:0x50000000007f1'}, received={'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_GROUP_ID': 'oid:0x50000000007fc', 'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_ID': 'oid:0x40000000007fa'}, key="oid:0x2d0000000007fe", table="ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER"
	[<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1465>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1418>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:427>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:232>]
test_sub_port_intf_oper_down_with_pending_neigh_route_tasks failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	Unexpected number of keys: expected=13, received=10 (('oid:0x60000000007e9', 'oid:0x60000000005c9', 'oid:0x60000000007f6', 'oid:0x60000000007ea', 'oid:0x60000000007e5', 'oid:0x60000000007e8', 'oid:0x60000000007e6', 'oid:0x60000000007f8', 'oid:0x60000000007f7', 'oid:0x60000000007e7')), table="ASIC_STATE:SAI_OBJECT_TYPE_ROUTER_INTERFACE"
	[<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1605>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1513>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:395>]
test_sub_port_intf_oper_down_with_pending_neigh_route_tasks failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	Unexpected number of keys: expected=13, received=10 (('oid:0x60000000007e9', 'oid:0x60000000005c9', 'oid:0x60000000007f6', 'oid:0x60000000007ea', 'oid:0x60000000007e5', 'oid:0x60000000007e8', 'oid:0x60000000007e6', 'oid:0x60000000007f8', 'oid:0x60000000007f7', 'oid:0x60000000007e7')), table="ASIC_STATE:SAI_OBJECT_TYPE_ROUTER_INTERFACE"
	[<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1605>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1513>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:395>]
test_nonflaky_dummy passed 1 out of the required 1 times. Success!
test_switch_attribute passed 1 out of the required 1 times. Success!

**Comment by amnsinghal** [comment]
> @amnsinghal build passed, failed at UT, could you help to take a look?
> 
> test_sub_port_intf_nhg_accel failed (1 runs remaining out of 2). <class 'AssertionError'> Unexpected number of keys: expected=6, received=4 (('oid:0x2d0000000007f3', 'oid:0x2d0000000007f4', 'oid:0x2d0000000007f2', 'oid:0x2d0000000007f5')), table="ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER" [<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1468>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1410>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:395>] test_sub_port_intf_nhg_accel failed; it passed 0 out of the required 1 times. <class 'AssertionError'> Expected field/value pairs not found: expected={'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_GROUP_ID': 'oid:0x50000000007f1'}, received={'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_GROUP_ID': 'oid:0x50000000007fc', 'SAI_NEXT_HOP_GROUP_MEMBER_ATTR_NEXT_HOP_ID': 'oid:0x40000000007fa'}, key="oid:0x2d0000000007fe", table="ASIC_STATE:SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER" [<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1465>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1418>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:427>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:232>] test_sub_port_intf_oper_down_with_pending_neigh_route_tasks failed (1 runs remaining out of 2). <class 'AssertionError'> Unexpected number of keys: expected=13, received=10 (('oid:0x60000000007e9', 'oid:0x60000000005c9', 'oid:0x60000000007f6', 'oid:0x60000000007ea', 'oid:0x60000000007e5', 'oid:0x60000000007e8', 'oid:0x60000000007e6', 'oid:0x60000000007f8', 'oid:0x60000000007f7', 'oid:0x60000000007e7')), table="ASIC_STATE:SAI_OBJECT_TYPE_ROUTER_INTERFACE" [<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1605>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1513>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:395>] test_sub_port_intf_oper_down_with_pending_neigh_route_tasks failed; it passed 0 out of the required 1 times. <class 'AssertionError'> Unexpected number of keys: expected=13, received=10 (('oid:0x60000000007e9', 'oid:0x60000000005c9', 'oid:0x60000000007f6', 'oid:0x60000000007ea', 'oid:0x60000000007e5', 'oid:0x60000000007e8', 'oid:0x60000000007e6', 'oid:0x60000000007f8', 'oid:0x60000000007f7', 'oid:0x60000000007e7')), table="ASIC_STATE:SAI_OBJECT_TYPE_ROUTER_INTERFACE" [<TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1605>, <TracebackEntry /agent/_work/1/s/tests/test_sub_port_intf.py:1513>, <TracebackEntry /agent/_work/1/s/tests/dvslib/dvs_database.py:395>] test_nonflaky_dummy passed 1 out of the required 1 times. Success! test_switch_attribute passed 1 out of the required 1 times. Success!

@StormLiangMS Thanks for checking, this UT is unrelated to my changes.
@prsunny @prgeor Any known issue or intermittent failure?

**Review by prsunny — APPROVED** [review]

**Comment by amnsinghal** [comment]
@prsunny Thanks for approving, can you pls rerun vstest, these 2 test failures don't look related to my changes.
```
test_createAndDeleteMultipleCounters
test_add_remove_port
```
Any known/intermittent issue?

**Comment by prsunny** [comment]
> @prsunny Thanks for approving, can you pls rerun vstest, these 2 test failures don't look related to my changes.
> 
> ```
> test_createAndDeleteMultipleCounters
> test_add_remove_port
> ```
> 
> Any known/intermittent issue?

no, not sure why its failing on 202305

**Comment by amnsinghal** [comment]
@StormLiangMS @prsunny All checks have passed, can you pls merge. Thanks!

**Pull request merged**
