### PR TITLE
[202205] [QoS] Enforce drop probability only for colors whose WRED are enabled (#2422)

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**

This is to cherry-pick #2422 to 202205 branch

**Why I did it**

Currently, there is a logic to enforce the drop probability if it is not explicitly designated for a color. However, the drop probability is not a mandatory attribute. It can incur vendor SAI complaints to set it when the color is disabled.
The logic was introduced from the very beginning (by PR #571) because no drop probability was defined in the QoS template at the time, which is no longer true.
So we will enforce drop probability only if it is not configured and the color is enabled.

**How I verified it**

Unit test and manual test

**Details if related**

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by stephenxs** [comment]
failed due to an irrelevant test case (warm reboot). retried.

**Comment by stephenxs** [comment]
all test cases passed but the pipeline failed due to 
```
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 4720fc4d-dd26-4bb0-a785-f8eda1852bd1
##[error]Artifact sonic-gcov already exists for build 150304.
Finishing: Publish gcov output
```

**Comment by liushilongbuaa** [comment]
> all test cases passed but the pipeline failed due to
> 
> ```
> ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 4720fc4d-dd26-4bb0-a785-f8eda1852bd1
> ##[error]Artifact sonic-gcov already exists for build 150304.
> Finishing: Publish gcov output
> ```

Test is not finished.
If only Gcov failed, go ahead.

**Comment by stephenxs** [comment]
> > all test cases passed but the pipeline failed due to
> > ```
> > ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 4720fc4d-dd26-4bb0-a785-f8eda1852bd1
> > ##[error]Artifact sonic-gcov already exists for build 150304.
> > Finishing: Publish gcov output
> > ```
> 
> Test is not finished. If only Gcov failed, go ahead.

Thanks.
The test had been finished with the only error like the above. I retriggered it later on...

**Comment by stephenxs** [comment]
Retried and the same. only Gcov failed. all test cases passed
image

**Comment by liushilongbuaa** [comment]
> Retried and the same. only Gcov failed. all test cases passed image

I see. Rerun will not help. It is pipeline issue.
I will fix it.

**Comment by stephenxs** [comment]
Closing this one as the original PR has been cherry picked to 202205.

**Pull request closed without merging**
