### PR TITLE
[vnetorch] fix keep old VxLAN endpoints after the same endpoints were repeatedly submitted

### PR DESCRIPTION
**Pull request by KostiantynYarovyiBf**
**What I did**
Add a case of updating an existing route, if the route exists and tries to set the same nexthop
**Why I did it**
orchagent does not call to remove a previous nexthop and try to create exist route if before twice set endpoint for this route and then change endpoint ip and set it again.

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@KostiantynYarovyiBf , can you provide the steps to repro the issue with an example?

**Comment by KostiantynYarovyiBf** [comment]
> @KostiantynYarovyiBf , can you provide the steps to repro the issue with an example?

STEPS TO REPRODUCE

1. Setup the specified env with t1 topo

2. Apply config below in DUT using specified commands and config snippets

sudo config load filename.json

`{    
    "VXLAN_TUNNEL": {"tunnel_v4": {"src_ip": "10.1.0.32"}},
    "VNET": {
        "Vnet_v4_in_v4-0": {
          "vxlan_tunnel": "tunnel_v4",
          "scope": "default",
          "vni": "10000",
          "peer_list": ""
      }},
      "INTERFACE": {
        "Ethernet240": {
          "vnet_name": "Vnet_v4_in_v4-0"
      }},
      "NEIGH": {
        "Ethernet240|201.0.0.101": {
          "family": "IPv4"
      }}
}`

3. Add vnet routes with command below and start observing  SONiC logs

docker exec -i swss swssconfig /dev/stdin < routes.json

`[{
"VNET_ROUTE_TUNNEL_TABLE:Vnet_v4_in_v4-0:150.0.5.1/32": {
    "endpoint": "100.0.6.1"},
  "OP": "SET"
}]`

4. No error Sonic logs for now
`Sep 13 10:11:16.371686 igk-4-dut NOTICE swss#swssconfig: :- main: Loading config from JSON file:/dev/stdin...
Sep 13 10:11:16.373391 igk-4-dut NOTICE swss#orchagent: :- createNextHopTunnel: NH tunnel create for tunnel_v4, ip 100.0.6.1, mac 00:00:00:00:00:00, vni 0`
And sairedis logs:
`|c|SAI_OBJECT_TYPE_NEXT_HOP:oid:0x4000000000ed8|SAI_NEXT_HOP_ATTR_TYPE=SAI_NEXT_HOP_TYPE_TUNNEL_ENCAP|SAI_NEXT_HOP_ATTR_IP=100.0.6.1|SAI_NEXT_HOP_ATTR_TUNNEL_ID=oid:0x2a000000000ed3
|c|SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"150.0.5.1/32","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000049"}|SAI_ROUTE_ENTRY_ATTR_NEXT_HOP_ID=oid:0x4000000000ed8
`
5. Rerun the command at step 3 to repeatedly add the same route config and notice error logs
Syslogs:
`NOTICE swss#swssconfig: :- main: Loading config from JSON file:/dev/stdin...
NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for tunnel_v4, ip 100.0.6.1, mac 00:00:00:00:00:00, vni 0
ERR swss#orchagent: :- meta_generic_validation_remove: object 0x40000000018ba reference count is 1, can't remove
ERR swss#orchagent: :- addOperation: VNET add operation error NH tunnel delete failed for 100.0.6.1`

And in this case, tried to remove nexthop but it failed because nexthop had a references. Therefore only reset nexthop for  exist route entry
`|s|SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"150.0.5.1/32","switch_id":"oid:0x21000000000000","vr":"oid:0x3000000000049"}|SAI_ROUTE_ENTRY_ATTR_NEXT_HOP_ID=oid:0x4000000000ed9
`
6. Change endpoint ip in the route.json file and try to set another endpoint
docker exec -i swss swssconfig /dev/stdin < routes.json

syslogs:
`NOTICE swss#swssconfig: :- main: Loading config from JSON file:/dev/stdin...
NOTICE swss#orchagent: :- removeNextHopTunnel: NH tunnel remove for tunnel_v4, ip 100.0.10.1, mac 00:00:00:00:00:00, vni 0
ERR swss#orchagent: :- meta_generic_validation_remove: object 0x4000000000ed9 reference count is 1, can't remove
ERR swss#orchagent: :- addOperation: VNET add operation error NH tunnel delete failed for 100.0.10.1`

`|c|SAI_OBJECT_TYPE_NEXT_HOP:oid:0x4000000000eda|SAI_NEXT_HOP_ATTR_TYPE=SAI_NEXT_HOP_TYPE_TUNNEL_ENCAP|SAI_NEXT_HOP_ATTR_IP=100.0.6.1|SAI_NEXT_HOP_ATTR_TUNNEL_ID=oid:0x2a000000000ed3
`

**Comment by KostiantynYarovyiBf** [comment]
> Thanks for the link PR and comment. In my approach, I try to delete the existing route and nexthop entry and if it happened, will update swss local date like syncd_nexthop_groups_[vnet] and syncd_nexthop_groups_[vnet][nhg].ref_count. But if SDK returns any error, this would not update because throw exception
https://github.com/sonic-net/sonic-swss/pull/2576/files#:~:text=throw%20std%3A%3Aruntime_error(err_msg)%3B

**Comment by KostiantynYarovyiBf** [comment]
close according to to exist fix in 202012 SONIC and moves this fix to master
https://github.com/sonic-net/sonic-swss/pull/2508

**Pull request closed without merging**
