### PR TITLE
[202211][ppi]: General code cleanup: remove unused methods (#2867)

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

**DEPENDS:**
1. https://github.com/sonic-net/sonic-swss/pull/2821

**HLD:** https://github.com/sonic-net/SONiC/pull/1084

**What I did**
* Removed unused code

**Why I did it**
* To complete code cleanup

**How I verified it**
* UT tests
* VS tests

**Details if related**
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2867

### CODE REVIEW

**Review by marian-pritsak — APPROVED** [review]

**Comment by nazariig** [comment]
@StormLiangMS can you please help to merge?

**Comment by nazariig** [comment]
@StormLiangMS can you please help to merge?

**Review by liat-grozovik — APPROVED** [review]

**Comment by nazariig** [comment]
@StormLiangMS just a kind reminder

**Comment by nazariig** [comment]
@StormLiangMS just a kind reminder

**Comment by nazariig** [comment]
@StormLiangMS just a kind reminder

**Comment by nazariig** [comment]
@StormLiangMS just a kind reminder

**Pull request merged**
