### PR TITLE
[dashrouteorch]: Rename dash route namespace (#2966)

### PR DESCRIPTION
**Pull request by Pterosaur**
**What I did**
Rename dash route namespace to follow the PR: https://github.com/sonic-net/sonic-dash-api/pull/9

**Why I did it**
The previous name `route_lpm` was inconsistent with convention.

**How I verified it**
Locally compile it.

**Details if related**

### CODE REVIEW

**Comment by Pterosaur** [comment]
Hi @prsunny , please help to merge this PR to 202311. It's cherry-picked from : https://github.com/sonic-net/sonic-swss/commit/fd852084d49f54bb15fa414eff4b2eab546ed64a

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@StormLiangMS for viz

**Pull request merged**
