### PR TITLE
Fix pipeline issue caused by urllib3 v2

### PR DESCRIPTION
**Pull request by liushilongbuaa**
**What I did**

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by nazariig — APPROVED** [review]

**Comment by nazariig** [comment]
@prsunny can you please help to merge?

**Review by prsunny — APPROVED** [review]

**Comment by keboliu** [comment]
Hi, @liushilongbuaa shall this also be cherry-picked for other branches, like the 202211 branch?

**Comment by liushilongbuaa** [comment]
> Hi, @liushilongbuaa shall this also be cherry-picked for other branches, like the 202211 branch?

If other branches break, yes.

**Comment by ayurkiv-nvda** [comment]
@prsunny can you please cherry-pick this fix to 202205 in order to fix errors that appear during PR checks?
```
<class 'docker.errors.DockerException'>
	Error while fetching server API version: request() got an unexpected keyword argument `'chunked''
```

**Comment by ayurkiv-nvda** [comment]
@yxieca can you please cherry-pick this PR to 202205 in order to fix errors that appear during PR checks?

```
<class 'docker.errors.DockerException'>
	Error while fetching server API version: request() got an unexpected keyword argument 'chunked'
```

**Comment by liuh-80** [comment]
@liushilongbuaa , the ADO is missing, if this PR no need cherry-pick, please remove the request label.

**Pull request merged**
