### PR TITLE
[orchagent] Do not set internal port count to the PortConfigDone DB value.

### PR DESCRIPTION
**Pull request by mint570**
**What I did**
Do not set internal port count to the PortConfigDone DB value.

**Why I did it**
Fix https://github.com/sonic-net/sonic-swss/issues/2904

### CODE REVIEW

**Comment by nazariig** [comment]
@mint570 do we need to remove port `count` attribute also from `portsyncd`?

**Comment by mint570** [comment]
@nazariig is that count in the DB being used by anything else?
If not, I can remove that from the DB.

**Comment by mint570** [comment]
Looks like the schema is used in other places as well: https://github.com/sonic-net/sonic-utilities/blob/3df1f18b0a339ab9d92cd8c28ad703a491b30b85/scripts/db_migrator.py#L180

To be safe, let's not remove the count from DB now.

**Review by dgsudharsan — APPROVED** [review]

**Review by nazariig — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Pull request merged**
