### PR TITLE
[Ci] Support to build sonic-swss-common

### PR DESCRIPTION
**Pull request by xumia**
**What I did**
[Ci] Support to build sonic-swss-common

**Why I did it**
It is to improve the chance to build successful rate on sonic-swss.
It removes the dependency of the build artifacts of sonic-swss-common in sonic-swss, always uses the latest code of the sonic-swss-common to build it.

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by vmittal-msft** [comment]
@theasianpianist we need this urgently for https://github.com/sonic-net/sonic-swss/pull/2618 to go in. #2618 is needed for pilot testing on chassis.

**Comment by theasianpianist** [comment]
Why do we want to start building swss-common instead of downloading artifacts?

**Comment by vmittal-msft** [comment]
Let me copy you on the email thread. sonic-swss compilation is failing due to sonic-swss-common package doesn't seem to be latest enough for this to compile. So why do we have such dependency ? and not directly compile to avoid such issues.

**Comment by xumia** [comment]
> Why do we want to start building swss-common instead of downloading artifacts?

The build sonic-swss-common is failed in test stage, it blocks the sonic-swss to use the lastest code, and the sonic-swss cannot be built successfully.

**Comment by xumia** [comment]
> > Why do we want to start building swss-common instead of downloading artifacts?
> 
> The build sonic-swss-common is failed in test stage, it blocks the sonic-swss to use the lastest code, and the sonic-swss cannot be built successfully. It reduces the dependency to wait for the result of the another pipeline.

**Comment by vmittal-msft** [comment]
As per @prsunny, this need to be included for 202205.
https://github.com/sonic-net/sonic-swss/pull/2648

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@theasianpianist , merging to unblock PR builds. Lets address any concerns as future commits.

**Pull request merged**
