### PR TITLE
[dash] Merge remote-tracking branch 'origin/master' into dash

### PR DESCRIPTION
**Pull request by Yakiv-Huryk**
**What I did**
Merge remote-tracking branch 'origin/master' into dash
**Why I did it**
To update the dash branch with the latest changes from the master branch.
**How I verified it**
Run dash tests
**Details if related**

### CODE REVIEW

**Comment by theasianpianist** [comment]
@Yakiv-Huryk please also change `azure-pipelines-dash.yml` to build with `bullseye` to fix the PR build

**Comment by Yakiv-Huryk** [comment]
> @Yakiv-Huryk please also change `azure-pipelines-dash.yml` to build with `bullseye` to fix the PR build

@theasianpianist I don't have access to the Azure pipeline.

**Comment by theasianpianist** [comment]
> > @Yakiv-Huryk please also change `azure-pipelines-dash.yml` to build with `bullseye` to fix the PR build
> 
> @theasianpianist I don't have access to the Azure pipeline.

I think you should be able to add a commit to this PR with the changes to the file, since they need to go in at the same time as the changes to the `.azure-pipelines` directory

**Comment by theasianpianist** [comment]
investigation build failure

**Comment by Pterosaur** [comment]
To specify the SKU to test_dash_vnet:
https://github.com/sonic-net/sonic-swss/pull/2780/commits/fde2d3cb2bc7909cdcb77dd2992c8aad9027b8aa

**Comment by theasianpianist** [comment]
FYI @oleksandrivantsiv needed to push this commit undoing some changes in your CRM PR in order for the VS tests to pass https://github.com/sonic-net/sonic-swss/pull/2770/commits/10a34f6a602b5c273cce885c4c0ecf552ea4e803. Let's revisit the changes once this is merged.

**Review by theasianpianist — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Pull request merged**
