### PR TITLE
Do not apply zero buffer profile list until all buffer pools are ready

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**

It was harmless unless there were too many messages indicating the depending buffer pools and profiles on some certain platforms, which triggers the syslog rate limit.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**Why I did it**

**How I verified it**

Manual and mock test

**Details if related**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
LGTM.
@stephenxs the PR is just pending final testing and ready for review?
@prsunny could you please review or suggest someone who can?

**Comment by prsunny** [comment]
@liat-grozovik , please move to 'ready' from 'draft'. @neethajohn to review

**Review by neethajohn — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prsunny we would like to have the fix in 202305 and 202311.
please let us know if this can be backport. @bingwang-ms  FYI

**Comment by StormLiangMS** [comment]
enhancement, no cherry pick to 202305.

**Comment by stephenxs** [comment]
> enhancement, no cherry pick to 202305.

Hi @StormLiangMS 
When the issue happens, there are a large number of messages, causing the system to drop messages from orchagent. As a result, some important message can be lost.

**Pull request merged**
