### PR TITLE
[orchagent] Change log level from ERR to WARN for pfc asym not supported

### PR DESCRIPTION
**Pull request by zhixzhu**
**What I did**
Change log level from ERR to WARN for pfc asym not supported

**Why I did it**
To address issue reported in https://migsonic.atlassian.net/browse/MIGSMSFT-473

**How I verified it**
Load new debian on testbed and check the log.
```
cisco@r2-lc0:~$ sudo cat /var/log/syslog | grep "queryPortAttrCapabilities"
Apr 25 22:52:26.787428 r2-lc0 WARNING swss1#orchagent: :- queryPortAttrCapabilities: Failed to get attribute(SAI_PORT_ATTR_PRIORITY_FLOW_CONTROL_TX) capabilities
Apr 25 22:52:26.787846 r2-lc0 WARNING swss1#orchagent: :- queryPortAttrCapabilities: Failed to get attribute(SAI_PORT_ATTR_PRIORITY_FLOW_CONTROL_RX) capabilities
cisco@r2-lc0:~$ 
```

**Details if related**

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
Bypassing coverage as this is a log level change

**Comment by zhixzhu** [comment]
@prsunny Could you help add label “Request for 202311 Branch“ and “Request for 202305 Branch“ to this PR? 
The error msg caused several test cases failed.

**Comment by abdosi** [comment]
@StormLiangMS : Can you please help cherry-pick of this.

**Comment by StormLiangMS** [comment]
@yxieca  for 202311 cherry pick.

**Pull request merged**
