### PR TITLE
[Marvell] platform renaming for innovium

### PR DESCRIPTION
**Pull request by krismarvell**
**What I did**
asic type checks for innovium platforms renamed
- innovium to marvell-teralynx

**Why I did it**
asictype is being renamed in sonic-buildimage repo and hence respective platform checks needs changes in swss

**How I verified it**
Run sonic-ptf on ACL and PFC modules to make sure the change does not impact existing functionality

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
This seems to be a breaking change to me. Can you confirm if this can be merged and not break existing platform?

**Comment by krismarvell** [comment]
@prsunny This PR wont break existing platform builds and also the functionalty of marvell(renamed as marvell-prestera) and innovium(renamed as marvell-teralynx) platforms. Also this has sonic-buildimage changes to enable respective platform builds in sonic master repo. Pls let me know if you see any specific concerns/breakages even with the additional changes in sonic-buildimage, sonic-sairedis and sonic-utilities PRs below.
sonic-buildimage: https://github.com/sonic-net/sonic-buildimage/pull/19829
sonic-sairedis: https://github.com/sonic-net/sonic-sairedis/pull/1408
sonic-utilties: https://github.com/sonic-net/sonic-utilities/pull/3474

**Comment by krismarvell** [comment]
@prsunny I see code coverage failing. Is there a way to bypass vstest ?

**Comment by prsunny** [comment]
@krismarvell , we can merge this PR once you confirm its ready. Do you've an order of merge dependency? Which PR should be going first?

**Comment by krismarvell** [comment]
@prsunny For the successful image build, i think it can be merged in any order and hence this swss change can be merged indepently. Pls let me know if you think otherwise. the sonic-swss submodule update into sonic-buildimage will happen subsequently ?

**Comment by prsunny** [comment]
> @prsunny For the successful image build, i think it can be merged in any order and hence this swss change can be merged indepently. Pls let me know if you think otherwise. the sonic-swss submodule update into sonic-buildimage will happen subsequently ?

submodule update is automated. It can happen in the next day itself. Is it going to break compilation?

**Comment by krismarvell** [comment]
@prsunny this merge is not going to break the build

**Comment by prsunny** [comment]
Platform renaming, and bypassing coverage

**Pull request merged**
