### PR TITLE
Add fabric counter rate mbps command handling.

### PR DESCRIPTION
**Pull request by jfeng-arista**
**What I did**
Add the orchagent handling for "show fabric counters rate mbps" command.

The HLD is at here

https://github.com/sonic-net/SONiC/blob/master/doc/voq/fabric.md

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Comment by jfeng-arista** [comment]
@arlakshm @vmittal-msft

**Comment by jfeng-arista** [comment]
test_chassis_system_lag_id_allocator_table_full failed, does not look like relates to this change . will start the swss tests again shortly

**Comment by jfeng-arista** [comment]
test_chassis_system_lag_id_allocator_table_full failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	LAG ID allocator table full error is not returned
assert '0' == '1'

not related to this change

**Comment by jfeng-arista** [comment]
test_chassis_system_lag_id_allocator_table_full failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	LAG ID allocator table full error is not returned
assert '0' == '1'

not  related to this chagne

**Review by arlakshm — APPROVED** [review]

**Pull request merged**
