### PR TITLE
[aclorch] Fix TODO: use SAI object API to query capabilities

### PR DESCRIPTION
**Pull request by stepanblyschak**
**What I did**

Resolved TODO

**Why I did it**

To resolve TODO

**How I verified it**

Build and run. Verify capabilities written in STATE DB:

```
127.0.0.1:6379[6]> hgetall  "SWITCH_CAPABILITY|switch"
...
13) "ACL_ACTION|PACKET_ACTION"
14) "DROP,FORWARD"
...
```

**Details if related**

### CODE REVIEW

**Review by volodymyrsamotiy — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@bingwang-ms kindly reminder to review

**Comment by bingwang-ms** [comment]
@liat-grozovik  Sorry, I missed this review. Can you please share the PR for supporting query `SAI_OBJECT_TYPE_ACL_ENTRY`? Thanks!

**Comment by stepanblyschak** [comment]
@bingwang-ms We have it already in sairedis for quite some time - https://github.com/sonic-net/sonic-sairedis/blob/master/lib/sai_redis_interfacequery.cpp#L145.
This API is already in use in sonic-swss - https://github.com/search?q=repo%3Asonic-net%2Fsonic-swss%20sai_query_attribute_enum_values_capability&type=code

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
