### PR TITLE
Add support for SEND_TO_INGRESS port table. 

### PR DESCRIPTION
**Pull request by baxia-lan**
**What I did**
Implement support for SEND_TO_INGRESS port table in CONFIG DB. 

HLD: https://github.com/sonic-net/SONiC/blob/master/doc/pins/send_to_ingress_hld.md
Required swss-common PR: https://github.com/sonic-net/sonic-swss-common/pull/792
**Why I did it**

**How I verified it**
Add below entry in config_db.json to use it.
```
    "SEND_TO_INGRESS_PORT": {
        "SEND_TO_INGRESS":{}
    },
```

The APPL DB(0) and APPL STATE DB(14)(previously 63) will have the entry added
image

**Details if related**

### CODE REVIEW

**Comment by baxia-lan** [comment]
@mint570

PTAL

**Comment by baxia-lan** [comment]
swss-common PR https://github.com/sonic-net/sonic-swss-common/pull/792 was submitted

**Review by mint570 — APPROVED** [review]

**Comment by baxia-lan** [comment]
@prsunny
Hi Prince, could you please take a look? Thanks!

**Comment by baxia-lan** [comment]
@prsunny
Hi Prince, could you please take a look? Thanks!

**Comment by baxia-lan** [comment]
The pytest failures(nexthop and acl) do not seem to related to the CL. cc. @prsunny and @marian-pritsak

**Comment by baxia-lan** [comment]
Kindly ping for review @prsunny @marian-pritsak

**Comment by baxia-lan** [comment]
Kindly ping for review/suggestions @prsunny @marian-pritsak

**Review by prsunny — APPROVED** [review]
lgtm. @dgsudharsan , can you take a look?

**Pull request merged**
