### PR TITLE
[ppi]: Relax port attributes validation

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)

**HLD:** https://github.com/sonic-net/SONiC/pull/1084

**What I did**
* Relaxed port attributes validation: decreased message severity

**Why I did it**
* To resolve `LogAnalyzer` failures during DPB test

**How I verified it**
1. Run DPB test

**Details if related**
* A W/A for: https://github.com/sonic-net/sonic-buildimage/issues/15999

### CODE REVIEW

**Review by marian-pritsak — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@nazariig how can we confirm this is correct for non DPB?
also, do we need this to go to other active branches?

**Comment by nazariig** [comment]
> @nazariig how can we confirm this is correct for non DPB? also, do we need this to go to other active branches?

@liat-grozovik this is already a part of `202211`. Need to align with `master`. It is just a message - no functional impact

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
