### PR TITLE
[acl]: fixed & refactored bind ACL table method.

### PR DESCRIPTION
**Pull request by nazarii-gnydyn**
**What I did**
Fixed bind ACL table method.

**Why I did it**
Applying ACL Table Group object without members created results in SAI error.

**How I verified it**
Created ACL table and binded it to port.

### CODE REVIEW

**Comment by lguohan** [comment]
we should be able to create empty acl table group and the bind to the port, I do not understand why sai won't allow us to do it.

**Comment by NStetskovych** [comment]
@lguohan yes, we can close it. But here is still the an issue with CRM counters:
https://github.com/Azure/sonic-swss/blob/201803/orchagent/portsorch.cpp#L556
(group_attr.value.s32  look at the group type but not to the stage)
We can provide separate PR or take this as it does not break anything.

**Comment by prsunny** [comment]
@NStetskovych , can you provide a separate PR for the CRM counter fix since without it, the counter value would be unpredictable.

**Comment by nazarii-gnydyn** [comment]
@lguohan You are right. Declining this because changes are redundant.

**Pull request closed without merging**
