### PR TITLE
Improve pytest speed by grouping 20 tests together.

### PR DESCRIPTION
**Pull request by mint570**
**What I did**
Group 20 tests together in pytest.

**Why I did it**
Hope this can improve the speed.

**How I verified it**
Presubmit test

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
Can we mark this PR ready?

**Comment by mint570** [comment]
> Can we mark this PR ready? or is there more work to be done?

It didn't improve much. About 10 min for grouping 10, and about 20 min for grouping 20.
I can try grouping 30.

BTW, the vs test seemed to be broken.

**Comment by prsunny** [comment]
> > Can we mark this PR ready? or is there more work to be done?
> 
> It didn't improve much. About 10 min for grouping 10, and about 20 min for grouping 20. I can try grouping 30.
> 
> BTW, the vs test seemed to be broken.

I actually see it improved. VS test issue was due to compilation.. its resolved now.

**Comment by mint570** [comment]
I don't see much improvement from 20 to 30. I will go with 20 then.

@prsunny this pr is ready after all tests pass.

**Comment by mint570** [comment]
@prsunny 
This PR is ready for review. Please take a look.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
