### PR TITLE
Enforce the order when the shared headroom pool is enabled

### PR DESCRIPTION
**Pull request by stephenxs**
**What I did**

Enforce the order when the shared headroom pool is enabled.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

**Why I did it**

The current flow to enable the shared headroom pool
1. Configure the shared headroom pool size or over-subscribe ratio
2. Update lossless buffer profiles with `xon == size`
3. Calculate and update the shared headroom pool size.

In step 2, the lossless buffer profiles have been updated to values as if the shared headroom pool is enabled. However, it is enabled only in step 3, which is inconsistent between steps 2 and 3. Therefore, we open the PR to guarantee the order.

The new flow
1. A user configures the shared headroom pool size or over-subscribe ratio
2. The dynamic buffer manager invokes the vendor-specific Lua plugin to calculate the shared headroom pool size
    - This is the step introduced in this PR to guarantee the shared headroom pool will be enabled in advance
    - On Nvidia platform, a non-zero shared headroom pool is returned in this stage if the user configures the over-subscribe ratio
3. If a non-zero shared headroom pool is returned, the dynamic buffer manager pushes the shared headroom pool size to APPL_DB.ingress_lossless_pool and blocks until it has been updated into APPL_STATE_DB.ingress_lossless_pool (which indicates the buffer orchagent finishes handling it)
4. The buffer manager updates the lossless buffer profiles
5. The buffer manager invokes the Lua plugin to calculate the shared headroom pool size.
6. The flow continues as normal.

**How I verified it**

Manually test and regression test

**Details if related**

### CODE REVIEW

**Comment by stephenxs** [comment]
Build failure doesn't look relevant to the PR itself.
```
Step 5/18 : RUN dpkg --purge python-swsscommon python3-swsscommon swss libsairedis sonic-db-cli libswsscommon libsaimetadata libsaivs syncd-vs
 ---> Running in aef760e247c4
dpkg: warning: ignoring request to remove python-swsscommon which isn't installed
(Reading database ... 31584 files and directories currently installed.)
Removing python3-swsscommon (1.0.0) ...
Removing swss (1.0.0) ...
Purging configuration files for swss (1.0.0) ...
Removing libsairedis (1.0.0) ...
Removing sonic-db-cli (1.0.0) ...
dpkg: dependency problems prevent removal of libswsscommon:
 sonic-eventd depends on libswsscommon (>= 1.0.0).

dpkg: error processing package libswsscommon (--purge):
 dependency problems - not removing
Removing libsaimetadata (1.0.0) ...
Removing libsaivs (1.0.0) ...
Removing syncd-vs (1.0.0) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
Purging configuration files for syncd-vs (1.0.0) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Errors were encountered while processing:
 libswsscommon
The command '/bin/sh -c dpkg --purge python-swsscommon python3-swsscommon swss libsairedis sonic-db-cli libswsscommon libsaimetadata libsaivs syncd-vs' returned a non-zero code: 1
##[error]Bash exited with code '1'.
Finishing: Build docker-sonic-vs
```

**Review by neethajohn — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@neethajohn can you please approve the backport PR?
@prsunny can you please merge this one?

**Pull request merged**
