### PR TITLE
[Orchagent] Add optional create_switch timeout parameter

### PR DESCRIPTION
**Pull request by pavannaregundi**
Backport of PR https://github.com/sonic-net/sonic-swss/pull/3258

**What I did**
Change adds optional create_switch timeout as command line parameter to orchagent.

**Why I did it**

**How I verified it**
Changes are verified to see passed timeout value is reflected only for create_switch api call from orchagent.

**Details if related**

### CODE REVIEW

**Comment by liushilongbuaa** [comment]
close and reopen to rerun validation

**Comment by Blueve** [comment]
ADO: 29208990

**Comment by liushilongbuaa** [comment]
@pavannaregundi , please rebase your code with latest 202311.
Pipeline failed on checkout step. It maybe github service issue.

**Pull request closed without merging**
