### PR TITLE
Fixed set admin_status for deleted subintf due to late notification

### PR DESCRIPTION
**Pull request by EdenGri**
**What I did**
Handled a race condition in intfmgrd which tries to immediately apply an admin_status SET notif after a DEL causing it to crash

**Why I did it**
Ignores errors on the set admin_status command for subinterface when the subinterface state is not OK.

**How I verified it**

**Details if related**
This PR reference to older PR that fix the same issue in portmgr: https://github.com/sonic-net/sonic-swss/pull/2431

### CODE REVIEW

**Review by dprital — APPROVED** [review]

**Review by dprital — COMMENTED** [review]
Please check why I don't see in the PR delete of add_ipv6_prefix_ut.cpp

**Comment by EdenGri** [comment]
> Please check why I don't see in the PR delete of add_ipv6_prefix_ut.cpp

GitHub handles it like rename of the file

**Review by dprital — APPROVED** [review]

**Comment by dprital** [comment]
@prsunny , Can you please review ?

**Review by prsunny — APPROVED** [review]

**Comment by yxieca** [comment]
@EdenGri  please help create separate PR for 202205 branch.

**Comment by EdenGri** [comment]
> This PR reference to older PR that fix the same issue in portmgr: #2431

NP: https://github.com/sonic-net/sonic-swss/pull/2704

**Pull request merged**
