### PR TITLE
Revert "[VS Test] Skip failing subport tests (#2370)"

### PR DESCRIPTION
**Pull request by liorghub**
This reverts commit 71752450e5d2c3c2f126aabddfe65b1d14344490.

**What I did**
Revert the commit that skips subport tests.

**Why I did it**
Add subport tests back to SWSS checkers.

**How I verified it**
Run SWSS checkers.

**Details if related**

### CODE REVIEW

**Comment by liorghub** [comment]
Sub port interface tests are passing.

```
2022-08-26T19:45:20.5736447Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_creation PASSED [ 82%]
2022-08-26T19:45:43.6259205Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_add_ip_addrs PASSED [ 82%]
2022-08-26T19:46:38.9704130Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_appl_db_proc_seq PASSED [ 82%]
2022-08-26T19:46:55.2397578Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_admin_status_change PASSED [ 83%]
2022-08-26T19:47:11.3537911Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_remove_ip_addrs PASSED [ 83%]
2022-08-26T19:48:17.7940280Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_removal PASSED [ 83%]
2022-08-26T19:48:45.8530048Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_mtu PASSED    [ 83%]
2022-08-26T19:51:22.2912884Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_nhg_accel PASSED [ 83%]
2022-08-26T19:53:42.3673089Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_oper_down_with_pending_neigh_route_tasks PASSED [ 83%]
2022-08-26T19:53:42.3686453Z test_sub_port_intf.py::test_nonflaky_dummy PASSED                        [ 84%]
```

**Comment by liorghub** [comment]
Sub port interface tests are passing (second time)

2022-08-26T19:45:20.5736447Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_creation PASSED [ 82%]
2022-08-26T19:45:43.6259205Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_add_ip_addrs PASSED [ 82%]
2022-08-26T19:46:38.9704130Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_appl_db_proc_seq PASSED [ 82%]
2022-08-26T19:46:55.2397578Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_admin_status_change PASSED [ 83%]
2022-08-26T19:47:11.3537911Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_remove_ip_addrs PASSED [ 83%]
2022-08-26T19:48:17.7940280Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_removal PASSED [ 83%]
2022-08-26T19:48:45.8530048Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_mtu PASSED    [ 83%]
2022-08-26T19:51:22.2912884Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_nhg_accel PASSED [ 83%]
2022-08-26T19:53:42.3673089Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_oper_down_with_pending_neigh_route_tasks PASSED [ 83%]
2022-08-26T19:53:42.3686453Z test_sub_port_intf.py::test_nonflaky_dummy PASSED                        [ 84%]

**Comment by liorghub** [comment]
Sub port interface tests are passing (second round).

```
2022-08-29T10:38:37.7845437Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_creation PASSED [ 39%]
2022-08-29T10:39:01.0323985Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_add_ip_addrs PASSED [ 40%]
2022-08-29T10:39:56.6278023Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_appl_db_proc_seq PASSED [ 40%]
2022-08-29T10:40:13.2443704Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_admin_status_change PASSED [ 41%]
2022-08-29T10:40:29.5115917Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_remove_ip_addrs PASSED [ 41%]
2022-08-29T10:41:37.9562588Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_removal PASSED [ 42%]
2022-08-29T10:42:06.2299272Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_mtu PASSED    [ 43%]
2022-08-29T10:44:45.5973714Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_nhg_accel PASSED [ 43%]
2022-08-29T10:47:10.1271329Z test_sub_port_intf.py::TestSubPortIntf::test_sub_port_intf_oper_down_with_pending_neigh_route_tasks PASSED [ 44%]
2022-08-29T10:47:10.1283681Z test_sub_port_intf.py::test_nonflaky_dummy PASSED                        [ 45%]
```

**Review by prsunny — APPROVED** [review]

**Pull request merged**
