### PR TITLE
Update FDB state table when , MAC entries are modified as dynamic_local.

### PR DESCRIPTION
**Pull request by prasanna-cls**
#### What I did 
When the FDB entry is updated as dynamic_local, then the FDB entry is updated in the FDB state table.

#### Why I did it
When the MCLAG synced FDB entries are modified as dynamic_local, then such entries are NOT updated in the FDB state table.
due to this, when these FDB entries are aged out, then the MCLAG module is not initimated about the MAC ageing, hence
there is no way the peer MCLAG node could flush these. it will remain as stale entries in the peer node.

#### How to verify it
Let both the MCLAG peers(A & B) both have locally learnt as well as synced in FDB entries.
when the MCLAG interface at node A is going down, then the synced in FDB entries in node B will be modified as dynamic_local.
when these entries are aged out at node B, then its flushed in node A as well.

without the fix, the FDB entries will remain stale at node A.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [X] 202205

### CODE REVIEW

**Review by gechiang — APPROVED** [review]
LGTM.

**Comment by gechiang** [comment]
@Praveen-Brcm can you also please review this change before we merge it in?
Thanks!

**Comment by Praveen-Brcm** [comment]
@gechiang The changes looks good and I have approved the changes. thanks

**Comment by gechiang** [comment]
Thanks @Praveen-Brcm for reviewing.
@prasanna-cls , is this fix needed to be backported to let's say 202205 branch?
Let me know which one is needed and I can add the label to reqeust for that branch.  If it can not be cleanly picked, you may have to submit a new PR from that corresponding branch.

**Comment by prasanna-cls** [comment]
> Thanks @Praveen-Brcm for reviewing. @prasanna-cls , is this fix needed to be backported to let's say 202205 branch? Let me know which one is needed and I can add the label to reqeust for that branch. If it can not be cleanly picked, you may have to submit a new PR from that corresponding branch.

Thanks @gechiang . Yes, May I request this pull request be backported to 202205 branch.

**Pull request merged**
