### PR TITLE
[202205] Modify coppmgr mergeConfig to support preserving copp tables through reboot

### PR DESCRIPTION
**Pull request by dprital**
This PR implements [fastboot] Preserve CoPP table HLD to improve fastboot flow (https://github.com/sonic-net/SONiC/pull/1107).

It is PR against 202205 of the following PR: https://github.com/sonic-net/sonic-swss/pull/2548
Should go together with PR: https://github.com/sonic-net/sonic-utilities/pull/2574

**What I did**

Modified coppmgr mergeConfig logic to support preserving copp tables contents through reboot. Handle duplicates, overwrites, unsupported keys preserved and new keys. According to https://github.com/sonic-net/SONiC/pull/1107

**Why I did it**

To shorten dataplane downtime on fast-reboot

**How I verified it**

Manual tests (community fast-reboot test)

**Details if related**

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
cherry pick was done. no need for this one

**Pull request closed without merging**
