### PR TITLE
[202211][CodeQL]: Use dependencies with relevant versions in azp template

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)

**What I did**
* Increase robustness of `CodeQL`: use only dependencies with the relevant versions

**Why I did it**
* To fix `CodeQL` compilation failures

**How I verified it**
1. Make a PR
2. Do a push

**Details if related**
* Backport from `master`: https://github.com/sonic-net/sonic-swss/pull/2845
* Resolves checker issue: https://github.com/sonic-net/sonic-swss/pull/2821
* Takes effect only after PR is merged

### CODE REVIEW

**Comment by nazariig** [comment]
@qiluo-msft / @prsunny would you please help to merge?

**Comment by nazariig** [comment]
@qiluo-msft / @prsunny this is a blocker for Port Profile Init feature. Would you please help to merge?

**Comment by prsunny** [comment]
@nazariig , is there a master branch PR for reference?
@liushilongbuaa and @xumia to signoff and merge
@StormLiangMS, @yxieca for viz

**Comment by nazariig** [comment]
> @nazariig , is there a master branch PR for reference? @liushilongbuaa and @xumia to signoff and merge @StormLiangMS, @yxieca for viz

@prsunny i have extended the description

**Comment by nazariig** [comment]
@liushilongbuaa / @xumia just a kind reminder

**Review by saiarcot895 — APPROVED** [review]

**Comment by nazariig** [comment]
@prsunny can you please merge this one too?

**Comment by liushilongbuaa** [comment]
image
It seems good from CodeQL in master branch.

**Comment by nazariig** [comment]
@prsunny / @qiluo-msft just a kind reminder

**Pull request merged**
