### PR TITLE
Modified the test file to remove click commands and do the REDIS-DB u…

### PR DESCRIPTION
**Pull request by Praveen-Brcm**
…pdates for MCLAG config commands.

**What I did**
Remove the CLICK commands in the test_mclag_cfg.py and use REDIS_DB for config updates.
**Why I did it**
To address #10245
**How I verified it**
VS tests.
**Details if related**

### CODE REVIEW

**Review by prsunny — APPROVED** [review]
Thanks @Praveen-Brcm for addressing this.

**Review by dgsudharsan — APPROVED** [review]

**Comment by Praveen-Brcm** [comment]
@dgsudharsan , @prsunny : Can you please help merge this change. Thanks.

**Review by dgsudharsan — APPROVED** [review]

**Pull request merged**
