### PR TITLE
[Chassis][202205][orchagent] : Support WRED profiles on system ports

### PR DESCRIPTION
**Pull request by vmittal-msft**
MSFT ADO: 24595422

What I did
Added support to apply wred profile on system ports

Why I did it
remote system ports were missing wred profile

How I verified it
Tested on sonic chassis

Details if related

### CODE REVIEW

**Comment by vmittal-msft** [comment]
Porting of https://github.com/sonic-net/sonic-swss/pull/2855 + VS tests verifying the functionlity

**Review by judyjoseph — APPROVED** [review]
lgtm

**Comment by gechiang** [comment]
@yxieca , @prsunny , @StormLiangMS ,  This is the PR that included the original fix (PR: https://github.com/sonic-net/sonic-swss/pull/2855) that got merged to master but was not allowed for 202211, 202305 and 202205 due to missing required unit testcases  + 
the missing PR unit test (https://github.com/sonic-net/sonic-swss/pull/2954#pullrequestreview-1751629463)  + 
a needed fix already merged in master (https://github.com/sonic-net/sonic-swss/pull/2947) that is needed also in other branches .

The idea is having this combined one single PR to be approved/merged in 202205 and then use it to cherry-pick into the other 2 branches which should reduce the potential cherry-pick conflict.

Thanks!

**Review by gechiang — APPROVED** [review]

**Comment by prsunny** [comment]
@yxieca for viz

**Comment by gechiang** [comment]
@vmittal-msft can you run on a pizzabox with this change in 202305 based code to ensure it will not cause regression before Storm pick this up into 2002305.
Thanks!

**Comment by gechiang** [comment]
@vmittal-msft do we really need this for 202211? if not, let's remove the label.

**Comment by StormLiangMS** [comment]
@gechiang  @vmittal-msft  remind for test.

**Pull request merged**
