### PR TITLE
[202205] [flowcounterrouter] Fix the Route remove flow for non-bound prefixes

### PR DESCRIPTION
**Pull request by vivekrnv**
**What I did**

Backport https://github.com/sonic-net/sonic-swss/pull/2691 to 202205

**Why I did it**

**How I verified it**

**Details if related**

### CODE REVIEW

**Review by Junchao-Mellanox — APPROVED** [review]

**Comment by vivekrnv** [comment]
vtest failures: 

Doesn't seem to be related to my changes. Seems this appeared in https://github.com/sonic-net/sonic-swss/pull/2360#issuecomment-1181796747 and seemingly fixed by https://github.com/sonic-net/sonic-swss/pull/2350. We might need to cherry-pick https://github.com/sonic-net/sonic-swss/pull/2350 to 2205
```
2023-03-15T21:32:58.7799524Z test_AclRuleAddWithoutTableDefinitionFails failed (1 runs remaining out of 2).
2023-03-15T21:32:58.7800476Z 	<class 'ValueError'>
2023-03-15T21:32:58.7801016Z 	filedescriptor out of range in select()
2023-03-15T21:32:58.7806344Z 	[<TracebackEntry /agent/_work/1/s/tests/conftest.py:1808>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:1787>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:601>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:457>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/models/containers.py:198>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py:19>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/exec_api.py:169>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:422>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:137>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:416>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:94>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:66>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:51>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:31>]
2023-03-15T21:32:58.7809808Z test_AclRuleAddWithoutTableDefinitionFails failed; it passed 0 out of the required 1 times.
2023-03-15T21:32:58.7810801Z 	<class 'ValueError'>
2023-03-15T21:32:58.7811321Z 	filedescriptor out of range in select()
2023-03-15T21:32:58.7815671Z 	[<TracebackEntry /agent/_work/1/s/tests/conftest.py:1808>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:1787>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:601>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:457>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/models/containers.py:198>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py:19>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/exec_api.py:169>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:422>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:137>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:416>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:94>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:66>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:51>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:31>]
2023-03-15T21:32:58.7819133Z test_MirrorSessionAddModifyAndDelete failed (1 runs remaining out of 2).
2023-03-15T21:32:58.7819871Z 	<class 'ValueError'>
2023-03-15T21:32:58.7820438Z 	filedescriptor out of range in select()
2023-03-15T21:32:58.7825141Z 	[<TracebackEntry /agent/_work/1/s/tests/conftest.py:1808>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:1787>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:601>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:457>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/models/containers.py:198>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py:19>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/exec_api.py:169>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:422>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:137>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:416>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:94>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:66>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:51>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:31>]
2023-03-15T21:32:58.7828300Z test_MirrorSessionAddModifyAndDelete failed; it passed 0 out of the required 1 times.
2023-03-15T21:32:58.7829227Z 	<class 'ValueError'>
2023-03-15T21:32:58.7829871Z 	filedescriptor out of range in select()
2023-03-15T21:32:58.7835567Z 	[<TracebackEntry /agent/_work/1/s/tests/conftest.py:1808>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:1775>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:406>, <TracebackEntry /agent/_work/1/s/tests/conftest.py:457>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/models/containers.py:198>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py:19>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/exec_api.py:169>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:422>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:137>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:416>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:94>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:66>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:51>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:31>]
2023-03-15T21:32:58.7839329Z 
2023-03-15T21:32:58.7839895Z ===End Flaky Test Report===
```

**Comment by dgsudharsan** [comment]
@liat-grozovik  This is already cherry-picked into 202205. So Closing this PR

**Pull request closed without merging**
